import { BookData } from './bookTypes';

interface GeneratePDFOptions {
  topic: string;
  bookData: BookData;
  coverImageUrl?: string;
  includeCoverPage?: boolean;
}

// 1. ASSETS
const KEY_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21 2-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0 3 3L22 7l-3-3m-3.5 3.5L19 4"/></svg>`;

// 2. HTML PARSER
const parseMarkdownToHtml = (text: string): string => {
  if (!text) return '';
  
  const lines = text.split('\n');
  let html = '';
  let inList = false;

  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip empty lines
    if (!trimmed) {
      if (inList) {
        html += '</ul>';
        inList = false;
      }
      continue;
    }

    // Headers - strip ALL # characters
    const headerMatch = trimmed.match(/^(#{1,6})\s*(.+)$/);
    if (headerMatch) {
      if (inList) { html += '</ul>'; inList = false; }
      const level = headerMatch[1].length;
      const content = headerMatch[2].replace(/^#+\s*/, '').trim();
      html += `<h${level}>${content}</h${level}>`;
      continue;
    }

    // Pro-Tips
    if (trimmed.startsWith('>')) {
      if (inList) { html += '</ul>'; inList = false; }
      const content = trimmed.slice(1).replace(/^PRO-TIP:?\s*/i, '').trim();
      html += `
        <div class="pro-tip-box">
          <div class="pro-tip-header">${KEY_ICON_SVG} PRO TIP</div>
          <div class="pro-tip-body">${content}</div>
        </div>
      `;
      continue;
    }

    // List items
    if (trimmed.match(/^[-*]\s+/)) {
      if (!inList) {
        html += '<ul class="bullet-list">';
        inList = true;
      }
      const content = trimmed.replace(/^[-*]\s+/, '');
      html += `<li>${content}</li>`;
      continue;
    }

    // Close list if we hit a non-list item
    if (inList) {
      html += '</ul>';
      inList = false;
    }

    // Images
    const imgMatch = trimmed.match(/!\[(.*?)\]\((.*?)\)/);
    if (imgMatch) {
      html += `<div class="img-wrapper"><img src="${imgMatch[2]}" alt="${imgMatch[1]}" /></div>`;
      continue;
    }

    // Regular paragraph - apply inline formatting
    let para = trimmed
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>');
    
    html += `<p>${para}</p>`;
  }

  if (inList) html += '</ul>';
  
  return html;
};

export const generateCleanPDF = async ({ 
  topic, 
  bookData,
}: GeneratePDFOptions): Promise<void> => {
  
  console.log('Generating Print View...');

  // 1. OPEN PRINT WINDOW
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export the PDF');
    return;
  }

  // 2. GENERATE CONTENT
  let htmlBody = '';

  // Title Page
  htmlBody += `
    <div class="page-container">
      <div class="title-page">
        <div class="title-content">
          <h1>${bookData.displayTitle || topic}</h1>
          ${bookData.subtitle ? `<p class="subtitle">${bookData.subtitle}</p>` : ''}
        </div>
        <p class="branding">LOOM & PAGE</p>
      </div>
    </div>
  `;

  // Copyright Page
  htmlBody += `
    <div class="page-container">
      <div class="copyright-page">
        <div class="copyright-content">
          <p><strong>Copyright © ${new Date().getFullYear()}</strong></p>
          <p>All rights reserved.</p>
          <p>Published by Loom & Page</p>
          <p>www.LoomandPage.com</p>
          <p style="margin-top: 1rem;">Book generated by Loom & Page AI Engine.</p>
          <p>First Edition: ${new Date().toLocaleString('default', { month: 'long', year: 'numeric' })}</p>
        </div>
      </div>
    </div>
  `;

  // TOC
  htmlBody += `
    <div class="page-container">
      <div class="toc-page">
        <h2>Table of Contents</h2>
        <div class="toc-list">
          ${(bookData.tableOfContents || []).map((ch: any) => `
            <div class="toc-item">
              <span>Chapter ${ch.chapter}</span>
              <span>${ch.title}</span>
            </div>
          `).join('')}
        </div>
      </div>
    </div>
  `;

  // Chapters
  const chapterKeys = Object.keys(bookData).filter(k => k.startsWith('chapter') && k.endsWith('Content'));
  const chapters = bookData.tableOfContents || chapterKeys.map((k, i) => ({ chapter: i + 1, title: `Chapter ${i + 1}` }));

  chapters.forEach((ch: any) => {
    const rawContent = (bookData[`chapter${ch.chapter}Content`] as string) || '';
    const processedContent = parseMarkdownToHtml(rawContent);

    htmlBody += `
      <div class="page-container">
        <div class="chapter-start">
          <div class="chapter-header">
            <p class="chapter-num">Chapter ${ch.chapter}</p>
            <h1>${ch.title}</h1>
            <div class="divider"></div>
          </div>
          <div class="chapter-body">
            ${processedContent}
          </div>
        </div>
      </div>
    `;
  });

  // 3. WRITE DOCUMENT
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
      <style>
        /* GLOBAL PRINT SETTINGS */
        @page {
          size: 6in 9in; /* KDP STANDARD SIZE */
          margin: 0; /* CRITICAL: Setting 0 hides browser header/footer clutter */
        }
        
        * {
          box-sizing: border-box;
        }
        
        body {
          margin: 0;
          /* We enforce physical margins inside the body content */
          padding: 0.75in 0.6in 0.75in 0.75in; 
          font-family: 'Playfair Display', Georgia, serif;
          font-size: 11pt;
          line-height: 1.6;
          color: #000;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }

        /* PAGE CONTAINERS */
        .page-container {
          width: 100%;
          break-after: page;
          page-break-after: always;
          position: relative;
        }

        /* TITLE PAGE */
        .title-page {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          text-align: center;
          height: 7.5in; /* 9in total - 1.5in vertical margins */
          padding-top: 2in;
        }
        .title-content h1 { font-size: 32pt; line-height: 1.1; margin-bottom: 0.5rem; text-transform: uppercase; }
        .subtitle { font-size: 14pt; font-style: italic; color: #555; }
        .branding { font-size: 9pt; letter-spacing: 2px; color: #888; text-transform: uppercase; margin-bottom: 0.5in; }

        /* COPYRIGHT PAGE */
        .copyright-page {
          display: flex;
          flex-direction: column;
          justify-content: flex-end;
          height: 7.5in;
        }
        .copyright-content p { margin: 0.2rem 0; font-size: 9pt; color: #444; }

        /* TOC */
        .toc-page h2 { text-align: center; margin-bottom: 2rem; font-size: 18pt; }
        .toc-list { margin-top: 1rem; }
        .toc-item { display: flex; justify-content: space-between; border-bottom: 1px solid #ddd; padding: 0.3rem 0; margin-bottom: 0.5rem; }

        /* CHAPTERS */
        .chapter-start { 
          margin-top: 1in; /* Visual space at top of page */
        }
        .chapter-header { text-align: center; margin-bottom: 2rem; }
        .chapter-num { font-size: 9pt; text-transform: uppercase; letter-spacing: 2px; color: #666; margin-bottom: 0.5rem; }
        .chapter-header h1 { font-size: 24pt; margin: 0; line-height: 1.2; }
        .divider { width: 40px; height: 1px; background: #ccc; margin: 1.5rem auto; }

        /* CONTENT STYLING */
        p { margin-bottom: 1rem; text-align: justify; widows: 2; orphans: 2; }
        h2 { font-size: 16pt; margin-top: 1.5rem; margin-bottom: 0.8rem; }
        h3 { font-size: 13pt; margin-top: 1.2rem; margin-bottom: 0.5rem; }
        
        /* IMAGES */
        .img-wrapper { text-align: center; margin: 1.5rem 0; break-inside: avoid; page-break-inside: avoid; }
        img { max-width: 100%; height: auto; border: 1px solid #eee; }

        /* PRO-TIP BOX */
        .pro-tip-box {
          background: #f9f9f9 !important;
          border-left: 4px solid #000 !important;
          padding: 1rem;
          margin: 1.5rem 0;
          break-inside: avoid;
          page-break-inside: avoid;
        }
        .pro-tip-header { font-size: 9pt; font-weight: bold; letter-spacing: 1px; margin-bottom: 0.5rem; display: flex; align-items: center; gap: 0.5rem; }
        .pro-tip-body { font-style: italic; font-size: 10.5pt; color: #333; }

        /* BULLETS */
        .bullet-list { padding-left: 1.5rem; margin-bottom: 1rem; }
        .bullet-list li { margin-bottom: 0.3rem; }
        
        /* Prevent page breaks inside elements */
        h1, h2, h3 {
          break-after: avoid;
          page-break-after: avoid;
        }
      </style>
    </head>
    <body>
      ${htmlBody}
      <script>
        // Wait for fonts and images to load before printing
        window.onload = function() {
          document.fonts.ready.then(function() {
            setTimeout(function() {
              window.print();
            }, 1500);
          });
        };
      </script>
    </body>
    </html>
  `);
  
  printWindow.document.close();
};
