import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja';

export interface Language {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', label: 'EN', nativeLabel: 'English' },
  { code: 'es', label: 'ES', nativeLabel: 'Español' },
  { code: 'fr', label: 'FR', nativeLabel: 'Français' },
  { code: 'de', label: 'DE', nativeLabel: 'Deutsch' },
  { code: 'it', label: 'IT', nativeLabel: 'Italiano' },
  { code: 'pt', label: 'PT', nativeLabel: 'Português' },
  { code: 'zh', label: 'ZH', nativeLabel: '中文' },
  { code: 'ja', label: 'JA', nativeLabel: '日本語' },
];

// Static UI translations
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    join: 'Join',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    search: 'Search',
    searchPlaceholder: 'What do you want to learn today?',
    whereToStay: 'Where to Stay',
    theVibe: 'The Vibe',
    downloadPDF: 'Download PDF',
    aCuratedGuide: 'A Curated Guide',
    printPreview: 'Print Preview',
    newGuide: 'New Guide',
    dashboard: 'Dashboard',
    myProjects: 'My Projects',
    saveToLibrary: 'Save to Library',
    localResources: 'Local Resources',
    enableLocation: 'Enable Location',
    chapterOne: 'Chapter One',
    chapterTwo: 'Chapter Two',
    chapterThree: 'Chapter Three',
    tableOfContents: 'Table of Contents',
    commonMistakes: 'Common Mistakes',
    proTips: 'Pro Tips',
    keyTakeaways: 'Key Takeaways',
    loading: 'Loading...',
    generating: 'Generating your guide...',
    tryAgain: 'Try Again',
    powered_by: 'Powered by',
    introductionTo: 'Introduction to',
    weaving: 'Weaving your guide...',
    downloadFreeSample: 'Download Free Sample (PDF)',
    unlockFullGuide: 'Unlock Full Artisan Guide',
    puttingItIntoPractice: 'Putting It Into Practice',
    saving: 'Saving...',
    saved: 'Saved to your library',
    learnAnything: 'Learn anything.',
    beautifulGuides: 'Beautiful, custom how-to guides crafted just for you.',
    searchExamples: 'Try: "Sourdough bread baking" or "Watercolor painting basics"',
    freeSampleDesc: 'The free sample includes the Cover, Table of Contents, and Chapter 1. The full guide unlocks all chapters.',
    fullAccessUnlocked: 'Full access unlocked',
    beginReading: 'Begin Reading',
    advancedOptions: 'Advanced Options',
    narrativeVoice: 'NARRATIVE VOICE',
    bookStructure: 'BOOK STRUCTURE',
    focusAreas: 'FOCUS AREAS',
    // Focus Area Labels
    focus_history: 'History',
    focus_wellness: 'Wellness',
    focus_nightlife: 'Nightlife',
    focus_art: 'Art & Design',
    focus_luxury: 'Luxury',
    focus_culture: 'Local Culture',
    focus_nature: 'Nature',
    // Focus Area Tooltips
    tooltip_history: 'Ancient stories, heritage sites, and cultural timelines',
    tooltip_wellness: 'Spas, retreats, meditation, and self-care rituals',
    tooltip_nightlife: 'Bars, clubs, live music, and after-dark scenes',
    tooltip_art: 'Galleries, architecture, studios, and creative spaces',
    tooltip_luxury: 'High-end experiences, exclusive venues, and premium services',
    tooltip_culture: 'Traditions, local customs, food markets, and community life',
    tooltip_nature: 'Parks, hiking trails, beaches, and outdoor adventures',
    // Voice Labels
    voice_insider: 'The Insider',
    voice_bestie: 'The Bestie',
    voice_poet: 'The Poet',
    voice_professor: 'The Professor',
    // Voice Tooltips
    tooltip_insider: 'Curated, cool, "If you know, you know"',
    tooltip_bestie: 'Sassy, confident, and witty',
    tooltip_poet: 'Dreamy, flowery, and romantic',
    tooltip_professor: 'Academic, educational, and clear',
    // Structure Labels
    structure_curated: 'Curated Guide',
    structure_playbook: 'Playbook',
    structure_balanced: 'Balanced',
    // Structure Tooltips
    tooltip_curated: 'Focus: Places, Hotels, Restaurants, Shopping',
    tooltip_playbook: 'Focus: Practices, How-to, Rituals, Education',
    tooltip_balanced: 'A 50/50 mix of Teaching and Destinations',
    // Weaving Steps
    weaving_step1: 'Gathering threads...',
    weaving_step2: 'Setting up the loom...',
    weaving_step3: 'Weaving chapters...',
    weaving_step4: 'Adding finishing touches...',
    weaving_step5: 'Almost ready...',
    // Chapter Status
    status_reading: 'Reading',
    status_expand: 'Expand',
    status_drafting: 'Drafting...',
    status_pending: 'Pending',
    status_locked: 'Locked',
    chapters: 'Chapters',
    contents: 'Contents',
    // Block Labels
    keyTakeaway: 'KEY TAKEAWAY',
    proTip: 'PRO TIP',
    // Download/Progress
    downloadFullGuide: 'Download Full Guide (PDF)',
    generatingPdf: 'Generating PDF...',
    weavingPages: 'Weaving... {count} pages',
    pleaseWaitChapters: 'Please wait for all chapters...',
    artisanWeaving: 'Our Artisan is weaving your custom details...',
    // Navigation
    prev: 'Prev',
    next: 'Next',
    pageTools: 'Page Tools',
    fit: 'Fit',
    fullSize: '100%',
    pageOf: 'of',
    chapterOf: 'Chapter {current} of {total}',
    // Footer
    aiDisclaimer: 'AI-generated content for creative inspiration only. Not professional advice.',
  },
  es: {
    join: 'Unirse',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    search: 'Buscar',
    searchPlaceholder: '¿Qué quieres aprender hoy?',
    whereToStay: 'Dónde Alojarse',
    theVibe: 'El Ambiente',
    downloadPDF: 'Descargar PDF',
    aCuratedGuide: 'Una Guía Curada',
    printPreview: 'Vista de Impresión',
    newGuide: 'Nueva Guía',
    dashboard: 'Panel',
    myProjects: 'Mis Proyectos',
    saveToLibrary: 'Guardar en Biblioteca',
    localResources: 'Recursos Locales',
    enableLocation: 'Activar Ubicación',
    chapterOne: 'Capítulo Uno',
    chapterTwo: 'Capítulo Dos',
    chapterThree: 'Capítulo Tres',
    tableOfContents: 'Índice',
    commonMistakes: 'Errores Comunes',
    proTips: 'Consejos Pro',
    keyTakeaways: 'Puntos Clave',
    loading: 'Cargando...',
    generating: 'Generando tu guía...',
    tryAgain: 'Intentar de Nuevo',
    powered_by: 'Impulsado por',
    introductionTo: 'Introducción a',
    weaving: 'Tejiendo tu guía...',
    downloadFreeSample: 'Descargar Muestra Gratis (PDF)',
    unlockFullGuide: 'Desbloquear Guía Artesanal Completa',
    puttingItIntoPractice: 'Poniéndolo en Práctica',
    saving: 'Guardando...',
    saved: 'Guardado en tu biblioteca',
    learnAnything: 'Aprende lo que quieras.',
    beautifulGuides: 'Guías personalizadas y hermosas creadas solo para ti.',
    searchExamples: 'Prueba: "Hacer pan de masa madre" o "Conceptos básicos de acuarela"',
    freeSampleDesc: 'La muestra gratuita incluye la portada, el índice y el capítulo 1. La guía completa desbloquea todos los capítulos.',
    fullAccessUnlocked: 'Acceso completo desbloqueado',
    beginReading: 'Comenzar a Leer',
    advancedOptions: 'Opciones Avanzadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUCTURA DEL LIBRO',
    focusAreas: 'ÁREAS DE ENFOQUE',
    // Focus Area Labels
    focus_history: 'Historia',
    focus_wellness: 'Bienestar',
    focus_nightlife: 'Vida Nocturna',
    focus_art: 'Arte y Diseño',
    focus_luxury: 'Lujo',
    focus_culture: 'Cultura Local',
    focus_nature: 'Naturaleza',
    // Focus Area Tooltips
    tooltip_history: 'Historias antiguas, sitios patrimoniales y cronologías culturales',
    tooltip_wellness: 'Spas, retiros, meditación y rituales de autocuidado',
    tooltip_nightlife: 'Bares, clubes, música en vivo y escenas nocturnas',
    tooltip_art: 'Galerías, arquitectura, estudios y espacios creativos',
    tooltip_luxury: 'Experiencias de alta gama, lugares exclusivos y servicios premium',
    tooltip_culture: 'Tradiciones, costumbres locales, mercados de comida y vida comunitaria',
    tooltip_nature: 'Parques, senderos, playas y aventuras al aire libre',
    // Voice Labels
    voice_insider: 'El Iniciado',
    voice_bestie: 'El/La Amigo/a',
    voice_poet: 'El Poeta',
    voice_professor: 'El Profesor',
    // Voice Tooltips
    tooltip_insider: 'Curado, genial, "Si sabes, sabes"',
    tooltip_bestie: 'Atrevido, seguro e ingenioso',
    tooltip_poet: 'Soñador, florido y romántico',
    tooltip_professor: 'Académico, educativo y claro',
    // Structure Labels
    structure_curated: 'Guía Curada',
    structure_playbook: 'Manual',
    structure_balanced: 'Equilibrado',
    // Structure Tooltips
    tooltip_curated: 'Enfoque: Lugares, Hoteles, Restaurantes, Compras',
    tooltip_playbook: 'Enfoque: Prácticas, Tutoriales, Rituales, Educación',
    tooltip_balanced: 'Una mezcla 50/50 de Enseñanza y Destinos',
    // Weaving Steps
    weaving_step1: 'Reuniendo hilos...',
    weaving_step2: 'Preparando el telar...',
    weaving_step3: 'Tejiendo capítulos...',
    weaving_step4: 'Añadiendo toques finales...',
    weaving_step5: 'Casi listo...',
    // Chapter Status
    status_reading: 'Leyendo',
    status_expand: 'Expandir',
    status_drafting: 'Redactando...',
    status_pending: 'Pendiente',
    status_locked: 'Bloqueado',
    chapters: 'Capítulos',
    contents: 'Contenido',
    // Block Labels
    keyTakeaway: 'PUNTO CLAVE',
    proTip: 'CONSEJO PRO',
    // Download/Progress
    downloadFullGuide: 'Descargar Guía Completa (PDF)',
    generatingPdf: 'Generando PDF...',
    weavingPages: 'Tejiendo... {count} páginas',
    pleaseWaitChapters: 'Por favor espera a todos los capítulos...',
    artisanWeaving: 'Nuestro Artesano está tejiendo tus detalles personalizados...',
    // Navigation
    prev: 'Ant',
    next: 'Sig',
    pageTools: 'Herramientas',
    fit: 'Ajustar',
    fullSize: '100%',
    pageOf: 'de',
    chapterOf: 'Capítulo {current} de {total}',
    // Footer
    aiDisclaimer: 'Contenido generado por IA solo para inspiración creativa. No es consejo profesional.',
  },
  fr: {
    join: 'Rejoindre',
    signIn: 'Se Connecter',
    signOut: 'Se Déconnecter',
    search: 'Rechercher',
    searchPlaceholder: "Que voulez-vous apprendre aujourd'hui?",
    whereToStay: 'Où Séjourner',
    theVibe: "L'Ambiance",
    downloadPDF: 'Télécharger PDF',
    aCuratedGuide: 'Le Guide Essentiel',
    printPreview: "Aperçu d'Impression",
    newGuide: 'Nouveau Guide',
    dashboard: 'Tableau de Bord',
    myProjects: 'Mes Projets',
    saveToLibrary: 'Sauvegarder',
    localResources: 'Ressources Locales',
    enableLocation: 'Activer la Localisation',
    chapterOne: 'Chapitre Un',
    chapterTwo: 'Chapitre Deux',
    chapterThree: 'Chapitre Trois',
    tableOfContents: 'Table des Matières',
    commonMistakes: 'Erreurs Courantes',
    proTips: 'Conseils Pro',
    keyTakeaways: 'Points Clés',
    loading: 'Chargement...',
    generating: 'Génération de votre guide...',
    tryAgain: 'Réessayer',
    powered_by: 'Propulsé par',
    introductionTo: 'Introduction à',
    weaving: 'Tissage de votre guide...',
    downloadFreeSample: 'Télécharger Échantillon Gratuit (PDF)',
    unlockFullGuide: 'Débloquer le Guide Artisan Complet',
    puttingItIntoPractice: 'Mise en Pratique',
    saving: 'Enregistrement...',
    saved: 'Enregistré dans votre bibliothèque',
    learnAnything: 'Apprenez tout.',
    beautifulGuides: 'Des guides personnalisés et magnifiques créés rien que pour vous.',
    searchExamples: 'Essayez: "Cuisson du pain au levain" ou "Bases de l\'aquarelle"',
    freeSampleDesc: 'L\'échantillon gratuit comprend la couverture, la table des matières et le chapitre 1. Le guide complet débloque tous les chapitres.',
    fullAccessUnlocked: 'Accès complet débloqué',
    beginReading: 'Commencer la Lecture',
    advancedOptions: 'Options Avancées',
    narrativeVoice: 'VOIX NARRATIVE',
    bookStructure: 'STRUCTURE DU LIVRE',
    focusAreas: 'DOMAINES DE FOCUS',
    // Focus Area Labels
    focus_history: 'Histoire',
    focus_wellness: 'Bien-être',
    focus_nightlife: 'Vie Nocturne',
    focus_art: 'Art & Design',
    focus_luxury: 'Luxe',
    focus_culture: 'Culture Locale',
    focus_nature: 'Nature',
    // Focus Area Tooltips
    tooltip_history: 'Histoires anciennes, sites patrimoniaux et chronologies culturelles',
    tooltip_wellness: 'Spas, retraites, méditation et rituels de bien-être',
    tooltip_nightlife: 'Bars, clubs, musique live et scènes nocturnes',
    tooltip_art: 'Galeries, architecture, studios et espaces créatifs',
    tooltip_luxury: 'Expériences haut de gamme, lieux exclusifs et services premium',
    tooltip_culture: 'Traditions, coutumes locales, marchés alimentaires et vie communautaire',
    tooltip_nature: 'Parcs, sentiers de randonnée, plages et aventures en plein air',
    // Voice Labels
    voice_insider: "L'Initié",
    voice_bestie: "L'Ami(e)",
    voice_poet: 'Le Poète',
    voice_professor: 'Le Professeur',
    // Voice Tooltips
    tooltip_insider: 'Sélectionné, cool, "Entre connaisseurs"',
    tooltip_bestie: 'Impertinent, confiant et spirituel',
    tooltip_poet: 'Rêveur, fleuri et romantique',
    tooltip_professor: 'Académique, éducatif et clair',
    // Structure Labels
    structure_curated: 'Guide Sélectionné',
    structure_playbook: 'Manuel Pratique',
    structure_balanced: 'Équilibré',
    // Structure Tooltips
    tooltip_curated: 'Focus: Lieux, Hôtels, Restaurants, Shopping',
    tooltip_playbook: 'Focus: Pratiques, Tutoriels, Rituels, Éducation',
    tooltip_balanced: 'Un mélange 50/50 d\'Enseignement et de Destinations',
    // Weaving Steps
    weaving_step1: 'Rassemblement des fils...',
    weaving_step2: 'Installation du métier à tisser...',
    weaving_step3: 'Tissage des chapitres...',
    weaving_step4: 'Ajout des touches finales...',
    weaving_step5: 'Presque prêt...',
    // Chapter Status
    status_reading: 'Lecture',
    status_expand: 'Développer',
    status_drafting: 'Rédaction...',
    status_pending: 'En attente',
    status_locked: 'Verrouillé',
    chapters: 'Chapitres',
    contents: 'Contenu',
    // Block Labels
    keyTakeaway: 'POINT CLÉ',
    proTip: 'CONSEIL PRO',
    // Download/Progress
    downloadFullGuide: 'Télécharger le Guide Complet (PDF)',
    generatingPdf: 'Génération du PDF...',
    weavingPages: 'Tissage... {count} pages',
    pleaseWaitChapters: 'Veuillez patienter pour tous les chapitres...',
    artisanWeaving: 'Notre Artisan tisse vos détails personnalisés...',
    // Navigation
    prev: 'Préc',
    next: 'Suiv',
    pageTools: 'Outils',
    fit: 'Ajuster',
    fullSize: '100%',
    pageOf: 'sur',
    chapterOf: 'Chapitre {current} sur {total}',
    // Footer
    aiDisclaimer: 'Contenu généré par IA pour inspiration créative uniquement. Ce n\'est pas un conseil professionnel.',
  },
  de: {
    join: 'Beitreten',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    search: 'Suchen',
    searchPlaceholder: 'Was möchten Sie heute lernen?',
    whereToStay: 'Unterkunft',
    theVibe: 'Die Atmosphäre',
    downloadPDF: 'PDF Herunterladen',
    aCuratedGuide: 'Ein Kuratierter Leitfaden',
    printPreview: 'Druckvorschau',
    newGuide: 'Neuer Leitfaden',
    dashboard: 'Dashboard',
    myProjects: 'Meine Projekte',
    saveToLibrary: 'Speichern',
    localResources: 'Lokale Ressourcen',
    enableLocation: 'Standort Aktivieren',
    chapterOne: 'Kapitel Eins',
    chapterTwo: 'Kapitel Zwei',
    chapterThree: 'Kapitel Drei',
    tableOfContents: 'Inhaltsverzeichnis',
    commonMistakes: 'Häufige Fehler',
    proTips: 'Profi-Tipps',
    keyTakeaways: 'Wichtigste Erkenntnisse',
    loading: 'Laden...',
    generating: 'Ihr Leitfaden wird erstellt...',
    tryAgain: 'Erneut Versuchen',
    powered_by: 'Unterstützt von',
    introductionTo: 'Einführung in',
    weaving: 'Weben Ihres Leitfadens...',
    downloadFreeSample: 'Kostenlose Probe Herunterladen (PDF)',
    unlockFullGuide: 'Vollständigen Handwerker-Leitfaden Freischalten',
    puttingItIntoPractice: 'In die Praxis Umsetzen',
    saving: 'Speichern...',
    saved: 'In Ihrer Bibliothek gespeichert',
    learnAnything: 'Lernen Sie alles.',
    beautifulGuides: 'Schöne, individuelle Anleitungen, die nur für Sie erstellt wurden.',
    searchExamples: 'Versuchen Sie: "Sauerteigbrot backen" oder "Aquarell-Grundlagen"',
    freeSampleDesc: 'Die kostenlose Probe enthält das Cover, das Inhaltsverzeichnis und Kapitel 1. Der vollständige Leitfaden schaltet alle Kapitel frei.',
    fullAccessUnlocked: 'Vollzugriff freigeschaltet',
    beginReading: 'Mit dem Lesen beginnen',
    advancedOptions: 'Erweiterte Optionen',
    narrativeVoice: 'ERZÄHLSTIMME',
    bookStructure: 'BUCHSTRUKTUR',
    focusAreas: 'SCHWERPUNKTE',
    // Focus Area Labels
    focus_history: 'Geschichte',
    focus_wellness: 'Wellness',
    focus_nightlife: 'Nachtleben',
    focus_art: 'Kunst & Design',
    focus_luxury: 'Luxus',
    focus_culture: 'Lokale Kultur',
    focus_nature: 'Natur',
    // Focus Area Tooltips
    tooltip_history: 'Alte Geschichten, Kulturerbestätten und kulturelle Zeitleisten',
    tooltip_wellness: 'Spas, Retreats, Meditation und Selbstpflege-Rituale',
    tooltip_nightlife: 'Bars, Clubs, Live-Musik und Nachtleben',
    tooltip_art: 'Galerien, Architektur, Studios und kreative Räume',
    tooltip_luxury: 'High-End-Erlebnisse, exklusive Orte und Premium-Services',
    tooltip_culture: 'Traditionen, lokale Bräuche, Lebensmittelmärkte und Gemeinschaftsleben',
    tooltip_nature: 'Parks, Wanderwege, Strände und Outdoor-Abenteuer',
    // Voice Labels
    voice_insider: 'Der Insider',
    voice_bestie: 'Der/Die Freund/in',
    voice_poet: 'Der Dichter',
    voice_professor: 'Der Professor',
    // Voice Tooltips
    tooltip_insider: 'Kuratiert, cool, "Wenn du es weißt, weißt du es"',
    tooltip_bestie: 'Frech, selbstbewusst und witzig',
    tooltip_poet: 'Verträumt, blumig und romantisch',
    tooltip_professor: 'Akademisch, lehrreich und klar',
    // Structure Labels
    structure_curated: 'Kuratierter Leitfaden',
    structure_playbook: 'Handbuch',
    structure_balanced: 'Ausgewogen',
    // Structure Tooltips
    tooltip_curated: 'Fokus: Orte, Hotels, Restaurants, Shopping',
    tooltip_playbook: 'Fokus: Praktiken, Anleitungen, Rituale, Bildung',
    tooltip_balanced: 'Eine 50/50 Mischung aus Lehre und Reisezielen',
    // Weaving Steps
    weaving_step1: 'Fäden sammeln...',
    weaving_step2: 'Webstuhl aufstellen...',
    weaving_step3: 'Kapitel weben...',
    weaving_step4: 'Letzte Details hinzufügen...',
    weaving_step5: 'Fast fertig...',
    // Chapter Status
    status_reading: 'Lesen',
    status_expand: 'Erweitern',
    status_drafting: 'Entwurf...',
    status_pending: 'Ausstehend',
    status_locked: 'Gesperrt',
    chapters: 'Kapitel',
    contents: 'Inhalt',
    // Block Labels
    keyTakeaway: 'WICHTIGSTE ERKENNTNIS',
    proTip: 'PROFI-TIPP',
    // Download/Progress
    downloadFullGuide: 'Vollständigen Leitfaden Herunterladen (PDF)',
    generatingPdf: 'PDF wird erstellt...',
    weavingPages: 'Weben... {count} Seiten',
    pleaseWaitChapters: 'Bitte warten Sie auf alle Kapitel...',
    artisanWeaving: 'Unser Handwerker webt Ihre individuellen Details...',
    // Navigation
    prev: 'Zurück',
    next: 'Weiter',
    pageTools: 'Werkzeuge',
    fit: 'Anpassen',
    fullSize: '100%',
    pageOf: 'von',
    chapterOf: 'Kapitel {current} von {total}',
    // Footer
    aiDisclaimer: 'KI-generierter Inhalt nur zur kreativen Inspiration. Kein professioneller Rat.',
  },
  it: {
    join: 'Unisciti',
    signIn: 'Accedi',
    signOut: 'Esci',
    search: 'Cerca',
    searchPlaceholder: 'Cosa vuoi imparare oggi?',
    whereToStay: 'Dove Alloggiare',
    theVibe: "L'Atmosfera",
    downloadPDF: 'Scarica PDF',
    aCuratedGuide: 'Una Guida Curata',
    printPreview: 'Anteprima di Stampa',
    newGuide: 'Nuova Guida',
    dashboard: 'Dashboard',
    myProjects: 'I Miei Progetti',
    saveToLibrary: 'Salva in Libreria',
    localResources: 'Risorse Locali',
    enableLocation: 'Attiva Posizione',
    chapterOne: 'Capitolo Uno',
    chapterTwo: 'Capitolo Due',
    chapterThree: 'Capitolo Tre',
    tableOfContents: 'Indice',
    commonMistakes: 'Errori Comuni',
    proTips: 'Consigli Pro',
    keyTakeaways: 'Punti Chiave',
    loading: 'Caricamento...',
    generating: 'Generazione della tua guida...',
    tryAgain: 'Riprova',
    powered_by: 'Alimentato da',
    introductionTo: 'Introduzione a',
    weaving: 'Tessendo la tua guida...',
    downloadFreeSample: 'Scarica Campione Gratuito (PDF)',
    unlockFullGuide: 'Sblocca la Guida Artigianale Completa',
    puttingItIntoPractice: 'Metterlo in Pratica',
    saving: 'Salvataggio...',
    saved: 'Salvato nella tua libreria',
    learnAnything: 'Impara qualsiasi cosa.',
    beautifulGuides: 'Guide personalizzate e belle create solo per te.',
    searchExamples: 'Prova: "Fare il pane con lievito madre" o "Basi dell\'acquerello"',
    freeSampleDesc: 'Il campione gratuito include la copertina, l\'indice e il capitolo 1. La guida completa sblocca tutti i capitoli.',
    fullAccessUnlocked: 'Accesso completo sbloccato',
    beginReading: 'Inizia a Leggere',
    advancedOptions: 'Opzioni Avanzate',
    narrativeVoice: 'VOCE NARRATIVA',
    bookStructure: 'STRUTTURA DEL LIBRO',
    focusAreas: 'AREE DI FOCUS',
    // Focus Area Labels
    focus_history: 'Storia',
    focus_wellness: 'Benessere',
    focus_nightlife: 'Vita Notturna',
    focus_art: 'Arte & Design',
    focus_luxury: 'Lusso',
    focus_culture: 'Cultura Locale',
    focus_nature: 'Natura',
    // Focus Area Tooltips
    tooltip_history: 'Storie antiche, siti del patrimonio e cronologie culturali',
    tooltip_wellness: 'Spa, ritiri, meditazione e rituali di cura di sé',
    tooltip_nightlife: 'Bar, club, musica dal vivo e scene notturne',
    tooltip_art: 'Gallerie, architettura, studi e spazi creativi',
    tooltip_luxury: 'Esperienze di alto livello, luoghi esclusivi e servizi premium',
    tooltip_culture: 'Tradizioni, usanze locali, mercati alimentari e vita comunitaria',
    tooltip_nature: 'Parchi, sentieri, spiagge e avventure all\'aperto',
    // Voice Labels
    voice_insider: "L'Iniziato",
    voice_bestie: "L'Amico/a",
    voice_poet: 'Il Poeta',
    voice_professor: 'Il Professore',
    // Voice Tooltips
    tooltip_insider: 'Curato, cool, "Se lo sai, lo sai"',
    tooltip_bestie: 'Sfacciato, sicuro e spiritoso',
    tooltip_poet: 'Sognante, fiorito e romantico',
    tooltip_professor: 'Accademico, educativo e chiaro',
    // Structure Labels
    structure_curated: 'Guida Curata',
    structure_playbook: 'Manuale',
    structure_balanced: 'Equilibrato',
    // Structure Tooltips
    tooltip_curated: 'Focus: Luoghi, Hotel, Ristoranti, Shopping',
    tooltip_playbook: 'Focus: Pratiche, Tutorial, Rituali, Educazione',
    tooltip_balanced: 'Un mix 50/50 di Insegnamento e Destinazioni',
    // Weaving Steps
    weaving_step1: 'Raccogliendo i fili...',
    weaving_step2: 'Preparando il telaio...',
    weaving_step3: 'Tessendo i capitoli...',
    weaving_step4: 'Aggiungendo i tocchi finali...',
    weaving_step5: 'Quasi pronto...',
    // Chapter Status
    status_reading: 'Lettura',
    status_expand: 'Espandi',
    status_drafting: 'Bozza...',
    status_pending: 'In attesa',
    status_locked: 'Bloccato',
    chapters: 'Capitoli',
    contents: 'Contenuto',
    // Block Labels
    keyTakeaway: 'PUNTO CHIAVE',
    proTip: 'CONSIGLIO PRO',
    // Download/Progress
    downloadFullGuide: 'Scarica Guida Completa (PDF)',
    generatingPdf: 'Generazione PDF...',
    weavingPages: 'Tessendo... {count} pagine',
    pleaseWaitChapters: 'Attendi tutti i capitoli...',
    artisanWeaving: 'Il nostro Artigiano sta tessendo i tuoi dettagli personalizzati...',
    // Navigation
    prev: 'Prec',
    next: 'Succ',
    pageTools: 'Strumenti',
    fit: 'Adatta',
    fullSize: '100%',
    pageOf: 'di',
    chapterOf: 'Capitolo {current} di {total}',
    // Footer
    aiDisclaimer: 'Contenuto generato da IA solo per ispirazione creativa. Non è un consiglio professionale.',
  },
  pt: {
    join: 'Junte-se',
    signIn: 'Entrar',
    signOut: 'Sair',
    search: 'Pesquisar',
    searchPlaceholder: 'O que você quer aprender hoje?',
    whereToStay: 'Onde Ficar',
    theVibe: 'A Vibe',
    downloadPDF: 'Baixar PDF',
    aCuratedGuide: 'Um Guia Curado',
    printPreview: 'Visualizar Impressão',
    newGuide: 'Novo Guia',
    dashboard: 'Painel',
    myProjects: 'Meus Projetos',
    saveToLibrary: 'Salvar na Biblioteca',
    localResources: 'Recursos Locais',
    enableLocation: 'Ativar Localização',
    chapterOne: 'Capítulo Um',
    chapterTwo: 'Capítulo Dois',
    chapterThree: 'Capítulo Três',
    tableOfContents: 'Índice',
    commonMistakes: 'Erros Comuns',
    proTips: 'Dicas Pro',
    keyTakeaways: 'Pontos-Chave',
    loading: 'Carregando...',
    generating: 'Gerando seu guia...',
    tryAgain: 'Tentar Novamente',
    powered_by: 'Desenvolvido por',
    introductionTo: 'Introdução a',
    weaving: 'Tecendo seu guia...',
    downloadFreeSample: 'Baixar Amostra Grátis (PDF)',
    unlockFullGuide: 'Desbloquear Guia Artesanal Completo',
    puttingItIntoPractice: 'Colocando em Prática',
    saving: 'Salvando...',
    saved: 'Salvo na sua biblioteca',
    learnAnything: 'Aprenda qualquer coisa.',
    beautifulGuides: 'Guias personalizados e bonitos criados só para você.',
    searchExamples: 'Tente: "Fazer pão de fermentação natural" ou "Básico de aquarela"',
    freeSampleDesc: 'A amostra grátis inclui a capa, o índice e o capítulo 1. O guia completo desbloqueia todos os capítulos.',
    fullAccessUnlocked: 'Acesso completo desbloqueado',
    beginReading: 'Começar a Ler',
    advancedOptions: 'Opções Avançadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUTURA DO LIVRO',
    focusAreas: 'ÁREAS DE FOCO',
    // Focus Area Labels
    focus_history: 'História',
    focus_wellness: 'Bem-estar',
    focus_nightlife: 'Vida Noturna',
    focus_art: 'Arte & Design',
    focus_luxury: 'Luxo',
    focus_culture: 'Cultura Local',
    focus_nature: 'Natureza',
    // Focus Area Tooltips
    tooltip_history: 'Histórias antigas, patrimônios culturais e cronologias',
    tooltip_wellness: 'Spas, retiros, meditação e rituais de autocuidado',
    tooltip_nightlife: 'Bares, clubes, música ao vivo e cenas noturnas',
    tooltip_art: 'Galerias, arquitetura, estúdios e espaços criativos',
    tooltip_luxury: 'Experiências de alto padrão, locais exclusivos e serviços premium',
    tooltip_culture: 'Tradições, costumes locais, mercados e vida comunitária',
    tooltip_nature: 'Parques, trilhas, praias e aventuras ao ar livre',
    // Voice Labels
    voice_insider: 'O Iniciado',
    voice_bestie: 'O/A Amigo/a',
    voice_poet: 'O Poeta',
    voice_professor: 'O Professor',
    // Voice Tooltips
    tooltip_insider: 'Curado, legal, "Se você sabe, você sabe"',
    tooltip_bestie: 'Atrevido, confiante e espirituoso',
    tooltip_poet: 'Sonhador, florido e romântico',
    tooltip_professor: 'Acadêmico, educacional e claro',
    // Structure Labels
    structure_curated: 'Guia Curado',
    structure_playbook: 'Manual',
    structure_balanced: 'Equilibrado',
    // Structure Tooltips
    tooltip_curated: 'Foco: Lugares, Hotéis, Restaurantes, Compras',
    tooltip_playbook: 'Foco: Práticas, Tutoriais, Rituais, Educação',
    tooltip_balanced: 'Uma mistura 50/50 de Ensino e Destinos',
    // Weaving Steps
    weaving_step1: 'Reunindo fios...',
    weaving_step2: 'Preparando o tear...',
    weaving_step3: 'Tecendo capítulos...',
    weaving_step4: 'Adicionando toques finais...',
    weaving_step5: 'Quase pronto...',
    // Chapter Status
    status_reading: 'Lendo',
    status_expand: 'Expandir',
    status_drafting: 'Redigindo...',
    status_pending: 'Pendente',
    status_locked: 'Bloqueado',
    chapters: 'Capítulos',
    contents: 'Conteúdo',
    // Block Labels
    keyTakeaway: 'PONTO-CHAVE',
    proTip: 'DICA PRO',
    // Download/Progress
    downloadFullGuide: 'Baixar Guia Completo (PDF)',
    generatingPdf: 'Gerando PDF...',
    weavingPages: 'Tecendo... {count} páginas',
    pleaseWaitChapters: 'Por favor aguarde todos os capítulos...',
    artisanWeaving: 'Nosso Artesão está tecendo seus detalhes personalizados...',
    // Navigation
    prev: 'Ant',
    next: 'Próx',
    pageTools: 'Ferramentas',
    fit: 'Ajustar',
    fullSize: '100%',
    pageOf: 'de',
    chapterOf: 'Capítulo {current} de {total}',
    // Footer
    aiDisclaimer: 'Conteúdo gerado por IA apenas para inspiração criativa. Não é aconselhamento profissional.',
  },
  zh: {
    join: '加入',
    signIn: '登录',
    signOut: '退出',
    search: '搜索',
    searchPlaceholder: '今天想学什么？',
    whereToStay: '住宿推荐',
    theVibe: '氛围',
    downloadPDF: '下载PDF',
    aCuratedGuide: '精选指南',
    printPreview: '打印预览',
    newGuide: '新指南',
    dashboard: '控制面板',
    myProjects: '我的项目',
    saveToLibrary: '保存到书库',
    localResources: '本地资源',
    enableLocation: '启用定位',
    chapterOne: '第一章',
    chapterTwo: '第二章',
    chapterThree: '第三章',
    tableOfContents: '目录',
    commonMistakes: '常见错误',
    proTips: '专业提示',
    keyTakeaways: '关键要点',
    loading: '加载中...',
    generating: '正在生成您的指南...',
    tryAgain: '重试',
    powered_by: '技术支持',
    introductionTo: '简介',
    weaving: '正在编织您的指南...',
    downloadFreeSample: '下载免费样本 (PDF)',
    unlockFullGuide: '解锁完整工匠指南',
    puttingItIntoPractice: '付诸实践',
    saving: '保存中...',
    saved: '已保存到您的书库',
    learnAnything: '学习任何东西。',
    beautifulGuides: '专为您打造的精美定制指南。',
    searchExamples: '试试："酸面包烘焙"或"水彩画基础"',
    freeSampleDesc: '免费样本包括封面、目录和第1章。完整指南解锁全部章节。',
    fullAccessUnlocked: '已解锁完整访问权限',
    beginReading: '开始阅读',
    advancedOptions: '高级选项',
    narrativeVoice: '叙事风格',
    bookStructure: '书籍结构',
    focusAreas: '关注领域',
    // Focus Area Labels
    focus_history: '历史',
    focus_wellness: '养生',
    focus_nightlife: '夜生活',
    focus_art: '艺术设计',
    focus_luxury: '奢华',
    focus_culture: '当地文化',
    focus_nature: '自然',
    // Focus Area Tooltips
    tooltip_history: '古老故事、文化遗产和历史时间线',
    tooltip_wellness: '水疗、静修、冥想和自我护理仪式',
    tooltip_nightlife: '酒吧、俱乐部、现场音乐和夜生活',
    tooltip_art: '画廊、建筑、工作室和创意空间',
    tooltip_luxury: '高端体验、专属场所和优质服务',
    tooltip_culture: '传统、当地习俗、美食市场和社区生活',
    tooltip_nature: '公园、徒步小径、海滩和户外冒险',
    // Voice Labels
    voice_insider: '内行人',
    voice_bestie: '闺蜜',
    voice_poet: '诗人',
    voice_professor: '教授',
    // Voice Tooltips
    tooltip_insider: '精选、时尚、"懂的都懂"',
    tooltip_bestie: '俏皮、自信、机智',
    tooltip_poet: '梦幻、浪漫、诗意',
    tooltip_professor: '学术、教育、清晰',
    // Structure Labels
    structure_curated: '精选指南',
    structure_playbook: '实用手册',
    structure_balanced: '均衡',
    // Structure Tooltips
    tooltip_curated: '重点：地点、酒店、餐厅、购物',
    tooltip_playbook: '重点：实践、教程、仪式、教育',
    tooltip_balanced: '教学与目的地的50/50混合',
    // Weaving Steps
    weaving_step1: '收集丝线...',
    weaving_step2: '准备织布机...',
    weaving_step3: '编织章节...',
    weaving_step4: '添加最后润色...',
    weaving_step5: '即将完成...',
    // Chapter Status
    status_reading: '阅读中',
    status_expand: '展开',
    status_drafting: '草拟中...',
    status_pending: '待处理',
    status_locked: '已锁定',
    chapters: '章节',
    contents: '内容',
    // Block Labels
    keyTakeaway: '关键要点',
    proTip: '专业提示',
    // Download/Progress
    downloadFullGuide: '下载完整指南 (PDF)',
    generatingPdf: '正在生成PDF...',
    weavingPages: '编织中... {count} 页',
    pleaseWaitChapters: '请等待所有章节完成...',
    artisanWeaving: '我们的工匠正在编织您的定制细节...',
    // Navigation
    prev: '上一页',
    next: '下一页',
    pageTools: '页面工具',
    fit: '适应',
    fullSize: '100%',
    pageOf: '/',
    chapterOf: '第{current}章 共{total}章',
    // Footer
    aiDisclaimer: 'AI生成内容仅供创意灵感参考。非专业建议。',
  },
  ja: {
    join: '参加',
    signIn: 'ログイン',
    signOut: 'ログアウト',
    search: '検索',
    searchPlaceholder: '今日は何を学びたいですか？',
    whereToStay: '宿泊先',
    theVibe: '雰囲気',
    downloadPDF: 'PDFダウンロード',
    aCuratedGuide: 'キュレーションガイド',
    printPreview: '印刷プレビュー',
    newGuide: '新しいガイド',
    dashboard: 'ダッシュボード',
    myProjects: 'マイプロジェクト',
    saveToLibrary: 'ライブラリに保存',
    localResources: '地域リソース',
    enableLocation: '位置情報を有効にする',
    chapterOne: '第1章',
    chapterTwo: '第2章',
    chapterThree: '第3章',
    tableOfContents: '目次',
    commonMistakes: 'よくある間違い',
    proTips: 'プロのヒント',
    keyTakeaways: '重要ポイント',
    loading: '読み込み中...',
    generating: 'ガイドを生成中...',
    tryAgain: '再試行',
    powered_by: '提供',
    introductionTo: '入門',
    weaving: 'ガイドを織り上げ中...',
    downloadFreeSample: '無料サンプルをダウンロード (PDF)',
    unlockFullGuide: '完全な職人ガイドをアンロック',
    puttingItIntoPractice: '実践する',
    saving: '保存中...',
    saved: 'ライブラリに保存されました',
    learnAnything: '何でも学べます。',
    beautifulGuides: 'あなただけのために作られた美しいカスタムガイド。',
    searchExamples: '試してみてください:「サワードウパンの焼き方」または「水彩画の基礎」',
    freeSampleDesc: '無料サンプルには表紙、目次、第1章が含まれています。完全ガイドは全章をアンロックします。',
    fullAccessUnlocked: 'フルアクセスがアンロックされました',
    beginReading: '読み始める',
    advancedOptions: '詳細オプション',
    narrativeVoice: 'ナラティブボイス',
    bookStructure: 'ブック構造',
    focusAreas: 'フォーカスエリア',
    // Focus Area Labels
    focus_history: '歴史',
    focus_wellness: 'ウェルネス',
    focus_nightlife: 'ナイトライフ',
    focus_art: 'アート＆デザイン',
    focus_luxury: 'ラグジュアリー',
    focus_culture: '地元の文化',
    focus_nature: '自然',
    // Focus Area Tooltips
    tooltip_history: '古代の物語、文化遺産、歴史年表',
    tooltip_wellness: 'スパ、リトリート、瞑想、セルフケア',
    tooltip_nightlife: 'バー、クラブ、ライブ音楽、ナイトライフ',
    tooltip_art: 'ギャラリー、建築、スタジオ、クリエイティブスペース',
    tooltip_luxury: 'ハイエンド体験、専用会場、プレミアムサービス',
    tooltip_culture: '伝統、地元の習慣、食品市場、コミュニティライフ',
    tooltip_nature: '公園、ハイキングトレイル、ビーチ、アウトドアアドベンチャー',
    // Voice Labels
    voice_insider: 'インサイダー',
    voice_bestie: '親友',
    voice_poet: '詩人',
    voice_professor: '教授',
    // Voice Tooltips
    tooltip_insider: 'キュレーション、クール、「知る人ぞ知る」',
    tooltip_bestie: '生意気、自信、ウィット',
    tooltip_poet: '夢のような、華やか、ロマンチック',
    tooltip_professor: 'アカデミック、教育的、明確',
    // Structure Labels
    structure_curated: 'キュレーションガイド',
    structure_playbook: 'プレイブック',
    structure_balanced: 'バランス',
    // Structure Tooltips
    tooltip_curated: 'フォーカス：場所、ホテル、レストラン、ショッピング',
    tooltip_playbook: 'フォーカス：実践、ハウツー、儀式、教育',
    tooltip_balanced: '教育と目的地の50/50ミックス',
    // Weaving Steps
    weaving_step1: '糸を集めています...',
    weaving_step2: '織機を準備しています...',
    weaving_step3: '章を織っています...',
    weaving_step4: '仕上げを追加しています...',
    weaving_step5: 'もうすぐ完成...',
    // Chapter Status
    status_reading: '読書中',
    status_expand: '展開',
    status_drafting: '下書き中...',
    status_pending: '保留中',
    status_locked: 'ロック済み',
    chapters: '章',
    contents: '内容',
    // Block Labels
    keyTakeaway: '重要ポイント',
    proTip: 'プロのヒント',
    // Download/Progress
    downloadFullGuide: '完全ガイドをダウンロード (PDF)',
    generatingPdf: 'PDFを生成中...',
    weavingPages: '織り上げ中... {count} ページ',
    pleaseWaitChapters: 'すべての章をお待ちください...',
    artisanWeaving: '職人があなたのカスタム詳細を織り上げています...',
    // Navigation
    prev: '前へ',
    next: '次へ',
    pageTools: 'ページツール',
    fit: 'フィット',
    fullSize: '100%',
    pageOf: '/',
    chapterOf: '第{current}章 / 全{total}章',
    // Footer
    aiDisclaimer: 'AI生成コンテンツはクリエイティブなインスピレーション専用です。専門的なアドバイスではありません。',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    // Try to load from localStorage
    const stored = localStorage.getItem('loom_language');
    if (stored && SUPPORTED_LANGUAGES.some(l => l.code === stored)) {
      return stored as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('loom_language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const currentLanguage = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
