import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja';

export interface Language {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', label: 'EN', nativeLabel: 'English' },
  { code: 'es', label: 'ES', nativeLabel: 'Español' },
  { code: 'fr', label: 'FR', nativeLabel: 'Français' },
  { code: 'de', label: 'DE', nativeLabel: 'Deutsch' },
  { code: 'it', label: 'IT', nativeLabel: 'Italiano' },
  { code: 'pt', label: 'PT', nativeLabel: 'Português' },
  { code: 'zh', label: 'ZH', nativeLabel: '中文' },
  { code: 'ja', label: 'JA', nativeLabel: '日本語' },
];

// Static UI translations
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    join: 'Join',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    search: 'Search',
    searchPlaceholder: 'What do you want to learn today?',
    whereToStay: 'Where to Stay',
    theVibe: 'The Vibe',
    downloadPDF: 'Download PDF',
    aCuratedGuide: 'A Curated Guide',
    printPreview: 'Print Preview',
    newGuide: 'New Guide',
    dashboard: 'Dashboard',
    myProjects: 'My Projects',
    saveToLibrary: 'Save to Library',
    localResources: 'Local Resources',
    enableLocation: 'Enable Location',
    chapterOne: 'Chapter One',
    chapterTwo: 'Chapter Two',
    chapterThree: 'Chapter Three',
    tableOfContents: 'Table of Contents',
    commonMistakes: 'Common Mistakes',
    proTips: 'Pro Tips',
    keyTakeaways: 'Key Takeaways',
    loading: 'Loading...',
    generating: 'Generating your guide...',
    tryAgain: 'Try Again',
    powered_by: 'Powered by',
    introductionTo: 'Introduction to',
    weaving: 'Weaving your guide...',
    downloadFreeSample: 'Download Free Sample (PDF)',
    unlockFullGuide: 'Unlock Full Artisan Guide',
    puttingItIntoPractice: 'Putting It Into Practice',
    saving: 'Saving...',
    saved: 'Saved to your library',
    learnAnything: 'Learn anything.',
    beautifulGuides: 'Beautiful, custom how-to guides crafted just for you.',
    searchExamples: 'Try: "Sourdough bread baking" or "Watercolor painting basics"',
    freeSampleDesc: 'The free sample includes the Cover, Table of Contents, and Chapter 1. The full guide unlocks all chapters.',
    fullAccessUnlocked: 'Full access unlocked',
    beginReading: 'Begin Reading',
    advancedOptions: 'Advanced Options',
    narrativeVoice: 'NARRATIVE VOICE',
    bookStructure: 'BOOK STRUCTURE',
    focusAreas: 'FOCUS AREAS',
  },
  es: {
    join: 'Unirse',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    search: 'Buscar',
    searchPlaceholder: '¿Qué quieres aprender hoy?',
    whereToStay: 'Dónde Alojarse',
    theVibe: 'El Ambiente',
    downloadPDF: 'Descargar PDF',
    aCuratedGuide: 'Una Guía Curada',
    printPreview: 'Vista de Impresión',
    newGuide: 'Nueva Guía',
    dashboard: 'Panel',
    myProjects: 'Mis Proyectos',
    saveToLibrary: 'Guardar en Biblioteca',
    localResources: 'Recursos Locales',
    enableLocation: 'Activar Ubicación',
    chapterOne: 'Capítulo Uno',
    chapterTwo: 'Capítulo Dos',
    chapterThree: 'Capítulo Tres',
    tableOfContents: 'Índice',
    commonMistakes: 'Errores Comunes',
    proTips: 'Consejos Pro',
    keyTakeaways: 'Puntos Clave',
    loading: 'Cargando...',
    generating: 'Generando tu guía...',
    tryAgain: 'Intentar de Nuevo',
    powered_by: 'Impulsado por',
    introductionTo: 'Introducción a',
    weaving: 'Weaving tu guía...',
    downloadFreeSample: 'Descargar Muestra Gratis (PDF)',
    unlockFullGuide: 'Desbloquear Guía Artesanal Completa',
    puttingItIntoPractice: 'Poniéndolo en Práctica',
    saving: 'Guardando...',
    saved: 'Guardado en tu biblioteca',
    learnAnything: 'Aprende lo que quieras.',
    beautifulGuides: 'Guías personalizadas y hermosas creadas solo para ti.',
    searchExamples: 'Prueba: "Hacer pan de masa madre" o "Conceptos básicos de acuarela"',
    freeSampleDesc: 'La muestra gratuita incluye la portada, el índice y el capítulo 1. La guía completa desbloquea todos los capítulos.',
    fullAccessUnlocked: 'Acceso completo desbloqueado',
    beginReading: 'Comenzar a Leer',
    advancedOptions: 'Opciones Avanzadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUCTURA DEL LIBRO',
    focusAreas: 'ÁREAS DE ENFOQUE',
  },
  fr: {
    join: 'Rejoindre',
    signIn: 'Se Connecter',
    signOut: 'Se Déconnecter',
    search: 'Rechercher',
    searchPlaceholder: "Que voulez-vous apprendre aujourd'hui?",
    whereToStay: 'Où Séjourner',
    theVibe: "L'Ambiance",
    downloadPDF: 'Télécharger PDF',
    aCuratedGuide: 'Le Guide Essentiel',
    printPreview: "Aperçu d'Impression",
    newGuide: 'Nouveau Guide',
    dashboard: 'Tableau de Bord',
    myProjects: 'Mes Projets',
    saveToLibrary: 'Sauvegarder',
    localResources: 'Ressources Locales',
    enableLocation: 'Activer la Localisation',
    chapterOne: 'Chapitre Un',
    chapterTwo: 'Chapitre Deux',
    chapterThree: 'Chapitre Trois',
    tableOfContents: 'Table des Matières',
    commonMistakes: 'Erreurs Courantes',
    proTips: 'Conseils Pro',
    keyTakeaways: 'Points Clés',
    loading: 'Chargement...',
    generating: 'Génération de votre guide...',
    tryAgain: 'Réessayer',
    powered_by: 'Propulsé par',
    introductionTo: 'Introduction à',
    weaving: 'Weaving votre guide...',
    downloadFreeSample: 'Télécharger Échantillon Gratuit (PDF)',
    unlockFullGuide: 'Débloquer le Guide Artisan Complet',
    puttingItIntoPractice: 'Mise en Pratique',
    saving: 'Enregistrement...',
    saved: 'Enregistré dans votre bibliothèque',
    learnAnything: 'Apprenez tout.',
    beautifulGuides: 'Des guides personnalisés et magnifiques créés rien que pour vous.',
    searchExamples: 'Essayez: "Cuisson du pain au levain" ou "Bases de l\'aquarelle"',
    freeSampleDesc: 'L\'échantillon gratuit comprend la couverture, la table des matières et le chapitre 1. Le guide complet débloque tous les chapitres.',
    fullAccessUnlocked: 'Accès complet débloqué',
    beginReading: 'Commencer la Lecture',
    advancedOptions: 'Options Avancées',
    narrativeVoice: 'VOIX NARRATIVE',
    bookStructure: 'STRUCTURE DU LIVRE',
    focusAreas: 'DOMAINES DE FOCUS',
  },
  de: {
    join: 'Beitreten',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    search: 'Suchen',
    searchPlaceholder: 'Was möchten Sie heute lernen?',
    whereToStay: 'Unterkunft',
    theVibe: 'Die Atmosphäre',
    downloadPDF: 'PDF Herunterladen',
    aCuratedGuide: 'Ein Kuratierter Leitfaden',
    printPreview: 'Druckvorschau',
    newGuide: 'Neuer Leitfaden',
    dashboard: 'Dashboard',
    myProjects: 'Meine Projekte',
    saveToLibrary: 'Speichern',
    localResources: 'Lokale Ressourcen',
    enableLocation: 'Standort Aktivieren',
    chapterOne: 'Kapitel Eins',
    chapterTwo: 'Kapitel Zwei',
    chapterThree: 'Kapitel Drei',
    tableOfContents: 'Inhaltsverzeichnis',
    commonMistakes: 'Häufige Fehler',
    proTips: 'Profi-Tipps',
    keyTakeaways: 'Wichtigste Erkenntnisse',
    loading: 'Laden...',
    generating: 'Ihr Leitfaden wird erstellt...',
    tryAgain: 'Erneut Versuchen',
    powered_by: 'Unterstützt von',
    introductionTo: 'Einführung in',
    weaving: 'Weaving Ihren Leitfaden...',
    downloadFreeSample: 'Kostenlose Probe Herunterladen (PDF)',
    unlockFullGuide: 'Vollständigen Handwerker-Leitfaden Freischalten',
    puttingItIntoPractice: 'In die Praxis Umsetzen',
    saving: 'Speichern...',
    saved: 'In Ihrer Bibliothek gespeichert',
    learnAnything: 'Lernen Sie alles.',
    beautifulGuides: 'Schöne, individuelle Anleitungen, die nur für Sie erstellt wurden.',
    searchExamples: 'Versuchen Sie: "Sauerteigbrot backen" oder "Aquarell-Grundlagen"',
    freeSampleDesc: 'Die kostenlose Probe enthält das Cover, das Inhaltsverzeichnis und Kapitel 1. Der vollständige Leitfaden schaltet alle Kapitel frei.',
    fullAccessUnlocked: 'Vollzugriff freigeschaltet',
    beginReading: 'Mit dem Lesen beginnen',
    advancedOptions: 'Erweiterte Optionen',
    narrativeVoice: 'ERZÄHLSTIMME',
    bookStructure: 'BUCHSTRUKTUR',
    focusAreas: 'SCHWERPUNKTE',
  },
  it: {
    join: 'Unisciti',
    signIn: 'Accedi',
    signOut: 'Esci',
    search: 'Cerca',
    searchPlaceholder: 'Cosa vuoi imparare oggi?',
    whereToStay: 'Dove Alloggiare',
    theVibe: "L'Atmosfera",
    downloadPDF: 'Scarica PDF',
    aCuratedGuide: 'Una Guida Curata',
    printPreview: 'Anteprima di Stampa',
    newGuide: 'Nuova Guida',
    dashboard: 'Dashboard',
    myProjects: 'I Miei Progetti',
    saveToLibrary: 'Salva in Libreria',
    localResources: 'Risorse Locali',
    enableLocation: 'Attiva Posizione',
    chapterOne: 'Capitolo Uno',
    chapterTwo: 'Capitolo Due',
    chapterThree: 'Capitolo Tre',
    tableOfContents: 'Indice',
    commonMistakes: 'Errori Comuni',
    proTips: 'Consigli Pro',
    keyTakeaways: 'Punti Chiave',
    loading: 'Caricamento...',
    generating: 'Generazione della tua guida...',
    tryAgain: 'Riprova',
    powered_by: 'Alimentato da',
    introductionTo: 'Introduzione a',
    weaving: 'Weaving la tua guida...',
    downloadFreeSample: 'Scarica Campione Gratuito (PDF)',
    unlockFullGuide: 'Sblocca la Guida Artigianale Completa',
    puttingItIntoPractice: 'Metterlo in Pratica',
    saving: 'Salvataggio...',
    saved: 'Salvato nella tua libreria',
    learnAnything: 'Impara qualsiasi cosa.',
    beautifulGuides: 'Guide personalizzate e belle create solo per te.',
    searchExamples: 'Prova: "Fare il pane con lievito madre" o "Basi dell\'acquerello"',
    freeSampleDesc: 'Il campione gratuito include la copertina, l\'indice e il capitolo 1. La guida completa sblocca tutti i capitoli.',
    fullAccessUnlocked: 'Accesso completo sbloccato',
    beginReading: 'Inizia a Leggere',
    advancedOptions: 'Opzioni Avanzate',
    narrativeVoice: 'VOCE NARRATIVA',
    bookStructure: 'STRUTTURA DEL LIBRO',
    focusAreas: 'AREE DI FOCUS',
  },
  pt: {
    join: 'Junte-se',
    signIn: 'Entrar',
    signOut: 'Sair',
    search: 'Pesquisar',
    searchPlaceholder: 'O que você quer aprender hoje?',
    whereToStay: 'Onde Ficar',
    theVibe: 'A Vibe',
    downloadPDF: 'Baixar PDF',
    aCuratedGuide: 'Um Guia Curado',
    printPreview: 'Visualizar Impressão',
    newGuide: 'Novo Guia',
    dashboard: 'Painel',
    myProjects: 'Meus Projetos',
    saveToLibrary: 'Salvar na Biblioteca',
    localResources: 'Recursos Locais',
    enableLocation: 'Ativar Localização',
    chapterOne: 'Capítulo Um',
    chapterTwo: 'Capítulo Dois',
    chapterThree: 'Capítulo Três',
    tableOfContents: 'Índice',
    commonMistakes: 'Erros Comuns',
    proTips: 'Dicas Pro',
    keyTakeaways: 'Pontos-Chave',
    loading: 'Carregando...',
    generating: 'Gerando seu guia...',
    tryAgain: 'Tentar Novamente',
    powered_by: 'Desenvolvido por',
    introductionTo: 'Introdução a',
    weaving: 'Weaving seu guia...',
    downloadFreeSample: 'Baixar Amostra Grátis (PDF)',
    unlockFullGuide: 'Desbloquear Guia Artesanal Completo',
    puttingItIntoPractice: 'Colocando em Prática',
    saving: 'Salvando...',
    saved: 'Salvo na sua biblioteca',
    learnAnything: 'Aprenda qualquer coisa.',
    beautifulGuides: 'Guias personalizados e bonitos criados só para você.',
    searchExamples: 'Tente: "Fazer pão de fermentação natural" ou "Básico de aquarela"',
    freeSampleDesc: 'A amostra grátis inclui a capa, o índice e o capítulo 1. O guia completo desbloqueia todos os capítulos.',
    fullAccessUnlocked: 'Acesso completo desbloqueado',
    beginReading: 'Começar a Ler',
    advancedOptions: 'Opções Avançadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUTURA DO LIVRO',
    focusAreas: 'ÁREAS DE FOCO',
  },
  zh: {
    join: '加入',
    signIn: '登录',
    signOut: '退出',
    search: '搜索',
    searchPlaceholder: '今天想学什么？',
    whereToStay: '住宿推荐',
    theVibe: '氛围',
    downloadPDF: '下载PDF',
    aCuratedGuide: '精选指南',
    printPreview: '打印预览',
    newGuide: '新指南',
    dashboard: '控制面板',
    myProjects: '我的项目',
    saveToLibrary: '保存到书库',
    localResources: '本地资源',
    enableLocation: '启用定位',
    chapterOne: '第一章',
    chapterTwo: '第二章',
    chapterThree: '第三章',
    tableOfContents: '目录',
    commonMistakes: '常见错误',
    proTips: '专业提示',
    keyTakeaways: '关键要点',
    loading: '加载中...',
    generating: '正在生成您的指南...',
    tryAgain: '重试',
    powered_by: '技术支持',
    introductionTo: '简介',
    weaving: 'Weaving 您的指南...',
    downloadFreeSample: '下载免费样本 (PDF)',
    unlockFullGuide: '解锁完整工匠指南',
    puttingItIntoPractice: '付诸实践',
    saving: '保存中...',
    saved: '已保存到您的书库',
    learnAnything: '学习任何东西。',
    beautifulGuides: '专为您打造的精美定制指南。',
    searchExamples: '试试："酸面包烘焙"或"水彩画基础"',
    freeSampleDesc: '免费样本包括封面、目录和第1章。完整指南解锁全部章节。',
    fullAccessUnlocked: '已解锁完整访问权限',
    beginReading: '开始阅读',
    advancedOptions: '高级选项',
    narrativeVoice: '叙事风格',
    bookStructure: '书籍结构',
    focusAreas: '关注领域',
  },
  ja: {
    join: '参加',
    signIn: 'ログイン',
    signOut: 'ログアウト',
    search: '検索',
    searchPlaceholder: '今日は何を学びたいですか？',
    whereToStay: '宿泊先',
    theVibe: '雰囲気',
    downloadPDF: 'PDFダウンロード',
    aCuratedGuide: 'キュレーションガイド',
    printPreview: '印刷プレビュー',
    newGuide: '新しいガイド',
    dashboard: 'ダッシュボード',
    myProjects: 'マイプロジェクト',
    saveToLibrary: 'ライブラリに保存',
    localResources: '地域リソース',
    enableLocation: '位置情報を有効にする',
    chapterOne: '第1章',
    chapterTwo: '第2章',
    chapterThree: '第3章',
    tableOfContents: '目次',
    commonMistakes: 'よくある間違い',
    proTips: 'プロのヒント',
    keyTakeaways: '重要ポイント',
    loading: '読み込み中...',
    generating: 'ガイドを生成中...',
    tryAgain: '再試行',
    powered_by: '提供',
    introductionTo: '入門',
    weaving: 'Weaving ガイドを作成中...',
    downloadFreeSample: '無料サンプルをダウンロード (PDF)',
    unlockFullGuide: '完全な職人ガイドをアンロック',
    puttingItIntoPractice: '実践する',
    saving: '保存中...',
    saved: 'ライブラリに保存されました',
    learnAnything: '何でも学べます。',
    beautifulGuides: 'あなただけのために作られた美しいカスタムガイド。',
    searchExamples: '試してみてください:「サワードウパンの焼き方」または「水彩画の基礎」',
    freeSampleDesc: '無料サンプルには表紙、目次、第1章が含まれています。完全ガイドは全章をアンロックします。',
    fullAccessUnlocked: 'フルアクセスがアンロックされました',
    beginReading: '読み始める',
    advancedOptions: '詳細オプション',
    narrativeVoice: 'ナラティブボイス',
    bookStructure: 'ブック構造',
    focusAreas: 'フォーカスエリア',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    // Try to load from localStorage
    const stored = localStorage.getItem('loom_language');
    if (stored && SUPPORTED_LANGUAGES.some(l => l.code === stored)) {
      return stored as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('loom_language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const currentLanguage = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
