import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja';

export interface Language {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', label: 'EN', nativeLabel: 'English' },
  { code: 'es', label: 'ES', nativeLabel: 'Español' },
  { code: 'fr', label: 'FR', nativeLabel: 'Français' },
  { code: 'de', label: 'DE', nativeLabel: 'Deutsch' },
  { code: 'it', label: 'IT', nativeLabel: 'Italiano' },
  { code: 'pt', label: 'PT', nativeLabel: 'Português' },
  { code: 'zh', label: 'ZH', nativeLabel: '中文' },
  { code: 'ja', label: 'JA', nativeLabel: '日本語' },
];

// Static UI translations
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    join: 'Join',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    search: 'Search',
    searchPlaceholder: 'What do you want to learn today?',
    whereToStay: 'Where to Stay',
    theVibe: 'The Vibe',
    downloadPDF: 'Download PDF',
    aCuratedGuide: 'A Curated Guide',
    printPreview: 'Print Preview',
    newGuide: 'New Guide',
    dashboard: 'Dashboard',
    myProjects: 'My Projects',
    saveToLibrary: 'Save to Library',
    localResources: 'Local Resources',
    enableLocation: 'Enable Location',
    chapterOne: 'Chapter One',
    chapterTwo: 'Chapter Two',
    chapterThree: 'Chapter Three',
    tableOfContents: 'Table of Contents',
    commonMistakes: 'Common Mistakes',
    proTips: 'Pro Tips',
    keyTakeaways: 'Key Takeaways',
    loading: 'Loading...',
    generating: 'Generating your guide...',
    tryAgain: 'Try Again',
    powered_by: 'Powered by',
    introductionTo: 'Introduction to',
    weaving: 'Weaving your guide...',
    downloadFreeSample: 'Download Free Sample (PDF)',
    unlockFullGuide: 'Unlock Full Artisan Guide',
    puttingItIntoPractice: 'Putting It Into Practice',
    saving: 'Saving...',
    saved: 'Saved to your library',
    learnAnything: 'Learn anything.',
    beautifulGuides: 'Beautiful, custom how-to guides crafted just for you.',
    searchExamples: 'Try: "Sourdough bread baking" or "Watercolor painting basics"',
    freeSampleDesc: 'The free sample includes the Cover, Table of Contents, and Chapter 1. The full guide unlocks all chapters.',
    fullAccessUnlocked: 'Full access unlocked',
    beginReading: 'Begin Reading',
    advancedOptions: 'Advanced Options',
    narrativeVoice: 'NARRATIVE VOICE',
    bookStructure: 'BOOK STRUCTURE',
    focusAreas: 'FOCUS AREAS',
    // Focus Area Labels
    focus_history: 'History',
    focus_wellness: 'Wellness',
    focus_nightlife: 'Nightlife',
    focus_art: 'Art & Design',
    focus_luxury: 'Luxury',
    focus_culture: 'Local Culture',
    focus_nature: 'Nature',
    // Focus Area Tooltips
    tooltip_history: 'Ancient stories, heritage sites, and cultural timelines',
    tooltip_wellness: 'Spas, retreats, meditation, and self-care rituals',
    tooltip_nightlife: 'Bars, clubs, live music, and after-dark scenes',
    tooltip_art: 'Galleries, architecture, studios, and creative spaces',
    tooltip_luxury: 'High-end experiences, exclusive venues, and premium services',
    tooltip_culture: 'Traditions, local customs, food markets, and community life',
    tooltip_nature: 'Parks, hiking trails, beaches, and outdoor adventures',
    // Voice Labels
    voice_insider: 'The Insider',
    voice_bestie: 'The Bestie',
    voice_poet: 'The Poet',
    voice_professor: 'The Professor',
    // Voice Tooltips
    tooltip_insider: 'Curated, cool, "If you know, you know"',
    tooltip_bestie: 'Sassy, confident, and witty',
    tooltip_poet: 'Dreamy, flowery, and romantic',
    tooltip_professor: 'Academic, educational, and clear',
    // Structure Labels
    structure_curated: 'Curated Guide',
    structure_playbook: 'Playbook',
    structure_balanced: 'Balanced',
    // Structure Tooltips
    tooltip_curated: 'Focus: Places, Hotels, Restaurants, Shopping',
    tooltip_playbook: 'Focus: Practices, How-to, Rituals, Education',
    tooltip_balanced: 'A 50/50 mix of Teaching and Destinations',
    // Weaving Steps
    weaving_step1: 'Gathering threads...',
    weaving_step2: 'Setting up the loom...',
    weaving_step3: 'Weaving chapters...',
    weaving_step4: 'Adding finishing touches...',
    weaving_step5: 'Almost ready...',
    // Chapter Status
    status_reading: 'Reading',
    status_expand: 'Expand',
    status_drafting: 'Drafting...',
    status_pending: 'Pending',
    status_locked: 'Locked',
    chapters: 'Chapters',
    contents: 'Contents',
    // Block Labels
    keyTakeaway: 'KEY TAKEAWAY',
    proTip: 'PRO TIP',
    // Download/Progress
    downloadFullGuide: 'Download Full Guide (PDF)',
    generatingPdf: 'Generating PDF...',
    weavingPages: 'Weaving... {count} pages',
    pleaseWaitChapters: 'Please wait for all chapters...',
    artisanWeaving: 'Our Artisan is weaving your custom details...',
    // Navigation
    prev: 'Prev',
    next: 'Next',
    pageTools: 'Page Tools',
    fit: 'Fit',
    fullSize: '100%',
    pageOf: 'of',
    chapterOf: 'Chapter {current} of {total}',
    // Page Tools Menu
    premiumEditingSuite: 'Premium Editing Suite',
    insertPageBefore: 'Insert Page Before',
    insertPageAfter: 'Insert Page After',
    searchGallery: 'Search Gallery',
    uploadOwnPhoto: 'Upload Own Photo',
    tryIt: 'Try it!',
    regenerateChapter: 'Regenerate Chapter {n}',
    editPageContent: 'Edit Page Content',
    deleteThisPage: 'Delete This Page',
    bwPrintMode: 'B&W Print Mode',
    bwPrintModeDesc: "Optimizes for Amazon's cheaper B&W printing",
    // Image States
    searchingArchives: 'Searching Archives...',
    searching: 'Searching...',
    aiSelected: 'AI-selected',
    imageNotFound: 'Image not found',
    // Cover Studio
    coverStudio: 'Cover Studio',
    previewStudio: 'Preview Studio',
    kdpCoverStudioTitle: 'KDP Cover Studio & Export Manager',
    // Tab Labels
    tabFront: 'Front',
    tabBack: 'Back',
    tabSpine: 'Spine',
    tabWrap: 'Wrap',
    tabPrep: 'Prep',
    tabRoyalty: '$$$',
    tabExport: 'Export',
    // Front Tab
    currentFrontCover: 'Current Front Cover',
    editCoverText: 'Edit Cover Text',
    viewOnly: 'View Only',
    titleLabel: 'Title',
    subtitleLabel: 'Subtitle',
    saveTextChanges: 'Save Text Changes',
    uploadYourOwnImage: 'Or Upload Your Own Image',
    uploadCustomCoverDesc: 'Upload a custom cover image (JPG, PNG, max 5MB)',
    uploadCoverImage: 'Upload Cover Image',
    customCoverImage: 'Custom Cover Image',
    unlockCoverEditing: 'Unlock Cover Editing',
    coverBranding: 'Cover Branding',
    brand: 'Brand',
    logo: 'Logo',
    uploadLogo: 'Upload Logo',
    changeLogo: 'Change Logo',
    reset: 'Reset',
    premium: 'Premium',
    noImage: 'No Image',
    uploading: 'Uploading...',
    // Back Tab
    currentBackCover: 'Current Back Cover',
    backCoverText: 'Back Cover Text',
    header: 'Header',
    // Export Tab
    completeKdpPackage: 'Complete KDP Package',
    kdpPackageDesc: 'Download everything you need for Amazon KDP in one ZIP file:',
    coverFile: 'Full wrap cover with spine',
    manuscriptFile: 'Interior text with TOC & images',
    kindleEbook: 'Kindle eBook format',
    kindleCover: 'eBook cover image',
    downloadKdpPackage: 'Download KDP Package',
    generatingPackage: 'Generating...',
    // Locked Tab Content
    amazonListingPrep: 'Amazon Listing Prep',
    amazonListingPrepDesc: 'Unlock to auto-generate your Best-Selling Description and Keywords with AI.',
    royaltyCalculator: 'Royalty Calculator',
    royaltyCalculatorDesc: 'Unlock to calculate your KDP royalties and optimize your pricing strategy.',
    // Prep Dashboard
    preparingMetadata: 'Preparing Amazon metadata...',
    generatingMetadata: 'Generating description, subtitle, and keywords...',
    pageCount: 'Page Count',
    spineLabel: 'Spine',
    trimLabel: 'Trim',
    bleedLabel: 'Bleed',
    bookDescription: 'Book Description',
    preview: 'Preview',
    html: 'HTML',
    previewFormatted: 'Preview (Formatted)',
    editHtml: 'Edit HTML',
    writeBestSellingDesc: 'Write Best-Selling Description',
    copyHtmlNote: 'Preview shows formatted text. Copy button copies raw HTML for Amazon KDP.',
    authorLabel: 'Author',
    generateSubtitle: 'Generate subtitle',
    keywords: 'Keywords',
    generateAll: 'Generate All',
    keywordsNote: 'Keywords avoid repeating words from your title for better Amazon ranking.',
    // Footer
    aiDisclaimer: 'AI-generated content for creative inspiration only. Not professional advice.',
  },
  es: {
    join: 'Unirse',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    search: 'Buscar',
    searchPlaceholder: '¿Qué quieres aprender hoy?',
    whereToStay: 'Dónde Alojarse',
    theVibe: 'El Ambiente',
    downloadPDF: 'Descargar PDF',
    aCuratedGuide: 'Una Guía Curada',
    printPreview: 'Vista de Impresión',
    newGuide: 'Nueva Guía',
    dashboard: 'Panel',
    myProjects: 'Mis Proyectos',
    saveToLibrary: 'Guardar en Biblioteca',
    localResources: 'Recursos Locales',
    enableLocation: 'Activar Ubicación',
    chapterOne: 'Capítulo Uno',
    chapterTwo: 'Capítulo Dos',
    chapterThree: 'Capítulo Tres',
    tableOfContents: 'Índice',
    commonMistakes: 'Errores Comunes',
    proTips: 'Consejos Pro',
    keyTakeaways: 'Puntos Clave',
    loading: 'Cargando...',
    generating: 'Generando tu guía...',
    tryAgain: 'Intentar de Nuevo',
    powered_by: 'Impulsado por',
    introductionTo: 'Introducción a',
    weaving: 'Tejiendo tu guía...',
    downloadFreeSample: 'Descargar Muestra Gratis (PDF)',
    unlockFullGuide: 'Desbloquear Guía Artesanal Completa',
    puttingItIntoPractice: 'Poniéndolo en Práctica',
    saving: 'Guardando...',
    saved: 'Guardado en tu biblioteca',
    learnAnything: 'Aprende lo que quieras.',
    beautifulGuides: 'Guías personalizadas y hermosas creadas solo para ti.',
    searchExamples: 'Prueba: "Hacer pan de masa madre" o "Conceptos básicos de acuarela"',
    freeSampleDesc: 'La muestra gratuita incluye la portada, el índice y el capítulo 1. La guía completa desbloquea todos los capítulos.',
    fullAccessUnlocked: 'Acceso completo desbloqueado',
    beginReading: 'Comenzar a Leer',
    advancedOptions: 'Opciones Avanzadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUCTURA DEL LIBRO',
    focusAreas: 'ÁREAS DE ENFOQUE',
    // Focus Area Labels
    focus_history: 'Historia',
    focus_wellness: 'Bienestar',
    focus_nightlife: 'Vida Nocturna',
    focus_art: 'Arte y Diseño',
    focus_luxury: 'Lujo',
    focus_culture: 'Cultura Local',
    focus_nature: 'Naturaleza',
    // Focus Area Tooltips
    tooltip_history: 'Historias antiguas, sitios patrimoniales y cronologías culturales',
    tooltip_wellness: 'Spas, retiros, meditación y rituales de autocuidado',
    tooltip_nightlife: 'Bares, clubes, música en vivo y escenas nocturnas',
    tooltip_art: 'Galerías, arquitectura, estudios y espacios creativos',
    tooltip_luxury: 'Experiencias de alta gama, lugares exclusivos y servicios premium',
    tooltip_culture: 'Tradiciones, costumbres locales, mercados de comida y vida comunitaria',
    tooltip_nature: 'Parques, senderos, playas y aventuras al aire libre',
    // Voice Labels
    voice_insider: 'El Iniciado',
    voice_bestie: 'El/La Amigo/a',
    voice_poet: 'El Poeta',
    voice_professor: 'El Profesor',
    // Voice Tooltips
    tooltip_insider: 'Curado, genial, "Si sabes, sabes"',
    tooltip_bestie: 'Atrevido, seguro e ingenioso',
    tooltip_poet: 'Soñador, florido y romántico',
    tooltip_professor: 'Académico, educativo y claro',
    // Structure Labels
    structure_curated: 'Guía Curada',
    structure_playbook: 'Manual',
    structure_balanced: 'Equilibrado',
    // Structure Tooltips
    tooltip_curated: 'Enfoque: Lugares, Hoteles, Restaurantes, Compras',
    tooltip_playbook: 'Enfoque: Prácticas, Tutoriales, Rituales, Educación',
    tooltip_balanced: 'Una mezcla 50/50 de Enseñanza y Destinos',
    // Weaving Steps
    weaving_step1: 'Reuniendo hilos...',
    weaving_step2: 'Preparando el telar...',
    weaving_step3: 'Tejiendo capítulos...',
    weaving_step4: 'Añadiendo toques finales...',
    weaving_step5: 'Casi listo...',
    // Chapter Status
    status_reading: 'Leyendo',
    status_expand: 'Expandir',
    status_drafting: 'Redactando...',
    status_pending: 'Pendiente',
    status_locked: 'Bloqueado',
    chapters: 'Capítulos',
    contents: 'Contenido',
    // Block Labels
    keyTakeaway: 'PUNTO CLAVE',
    proTip: 'CONSEJO PRO',
    // Download/Progress
    downloadFullGuide: 'Descargar Guía Completa (PDF)',
    generatingPdf: 'Generando PDF...',
    weavingPages: 'Tejiendo... {count} páginas',
    pleaseWaitChapters: 'Por favor espera a todos los capítulos...',
    artisanWeaving: 'Nuestro Artesano está tejiendo tus detalles personalizados...',
    // Navigation
    prev: 'Ant',
    next: 'Sig',
    pageTools: 'Herramientas',
    fit: 'Ajustar',
    fullSize: '100%',
    pageOf: 'de',
    chapterOf: 'Capítulo {current} de {total}',
    // Page Tools Menu
    premiumEditingSuite: 'Suite de Edición Premium',
    insertPageBefore: 'Insertar Página Antes',
    insertPageAfter: 'Insertar Página Después',
    searchGallery: 'Buscar en Galería',
    uploadOwnPhoto: 'Subir Tu Foto',
    tryIt: '¡Pruébalo!',
    regenerateChapter: 'Regenerar Capítulo {n}',
    editPageContent: 'Editar Contenido de Página',
    deleteThisPage: 'Eliminar Esta Página',
    bwPrintMode: 'Modo Impresión B&N',
    bwPrintModeDesc: 'Optimiza para la impresión B&N más económica de Amazon',
    // Image States
    searchingArchives: 'Buscando en Archivos...',
    searching: 'Buscando...',
    aiSelected: 'Seleccionado por IA',
    imageNotFound: 'Imagen no encontrada',
    // Cover Studio
    coverStudio: 'Estudio de Portada',
    previewStudio: 'Estudio de Vista Previa',
    kdpCoverStudioTitle: 'Estudio de Portada KDP y Gestor de Exportación',
    // Tab Labels
    tabFront: 'Frontal',
    tabBack: 'Trasera',
    tabSpine: 'Lomo',
    tabWrap: 'Completa',
    tabPrep: 'Prep',
    tabRoyalty: '$$$',
    tabExport: 'Exportar',
    // Front Tab
    currentFrontCover: 'Portada Frontal Actual',
    editCoverText: 'Editar Texto de Portada',
    viewOnly: 'Solo Vista',
    titleLabel: 'Título',
    subtitleLabel: 'Subtítulo',
    saveTextChanges: 'Guardar Cambios de Texto',
    uploadYourOwnImage: 'O Sube Tu Propia Imagen',
    uploadCustomCoverDesc: 'Sube una imagen de portada personalizada (JPG, PNG, máx 5MB)',
    uploadCoverImage: 'Subir Imagen de Portada',
    customCoverImage: 'Imagen de Portada Personalizada',
    unlockCoverEditing: 'Desbloquear Edición de Portada',
    coverBranding: 'Marca de Portada',
    brand: 'Marca',
    logo: 'Logo',
    uploadLogo: 'Subir Logo',
    changeLogo: 'Cambiar Logo',
    reset: 'Restablecer',
    premium: 'Premium',
    noImage: 'Sin Imagen',
    uploading: 'Subiendo...',
    // Back Tab
    currentBackCover: 'Contraportada Actual',
    backCoverText: 'Texto de Contraportada',
    header: 'Encabezado',
    // Export Tab
    completeKdpPackage: 'Paquete KDP Completo',
    kdpPackageDesc: 'Descarga todo lo que necesitas para Amazon KDP en un archivo ZIP:',
    coverFile: 'Portada completa con lomo',
    manuscriptFile: 'Texto interior con TOC e imágenes',
    kindleEbook: 'Formato eBook Kindle',
    kindleCover: 'Imagen de portada eBook',
    downloadKdpPackage: 'Descargar Paquete KDP',
    generatingPackage: 'Generando...',
    // Locked Tab Content
    amazonListingPrep: 'Preparación de Listado Amazon',
    amazonListingPrepDesc: 'Desbloquea para auto-generar tu Descripción y Palabras Clave Best-Seller con IA.',
    royaltyCalculator: 'Calculadora de Regalías',
    royaltyCalculatorDesc: 'Desbloquea para calcular tus regalías KDP y optimizar tu estrategia de precios.',
    // Prep Dashboard
    preparingMetadata: 'Preparando metadatos de Amazon...',
    generatingMetadata: 'Generando descripción, subtítulo y palabras clave...',
    pageCount: 'Número de Páginas',
    spineLabel: 'Lomo',
    trimLabel: 'Formato',
    bleedLabel: 'Sangrado',
    bookDescription: 'Descripción del Libro',
    preview: 'Vista Previa',
    html: 'HTML',
    previewFormatted: 'Vista Previa (Formateada)',
    editHtml: 'Editar HTML',
    writeBestSellingDesc: 'Escribir Descripción Best-Seller',
    copyHtmlNote: 'La vista previa muestra texto formateado. El botón copiar copia HTML crudo para Amazon KDP.',
    authorLabel: 'Autor',
    generateSubtitle: 'Generar subtítulo',
    keywords: 'Palabras Clave',
    generateAll: 'Generar Todo',
    keywordsNote: 'Las palabras clave evitan repetir palabras de tu título para mejor ranking en Amazon.',
    // Footer
    aiDisclaimer: 'Contenido generado por IA solo para inspiración creativa. No es consejo profesional.',
  },
  fr: {
    join: 'Rejoindre',
    signIn: 'Se Connecter',
    signOut: 'Se Déconnecter',
    search: 'Rechercher',
    searchPlaceholder: "Que voulez-vous apprendre aujourd'hui?",
    whereToStay: 'Où Séjourner',
    theVibe: "L'Ambiance",
    downloadPDF: 'Télécharger PDF',
    aCuratedGuide: 'Le Guide Essentiel',
    printPreview: "Aperçu d'Impression",
    newGuide: 'Nouveau Guide',
    dashboard: 'Tableau de Bord',
    myProjects: 'Mes Projets',
    saveToLibrary: 'Sauvegarder',
    localResources: 'Ressources Locales',
    enableLocation: 'Activer la Localisation',
    chapterOne: 'Chapitre Un',
    chapterTwo: 'Chapitre Deux',
    chapterThree: 'Chapitre Trois',
    tableOfContents: 'Table des Matières',
    commonMistakes: 'Erreurs Courantes',
    proTips: 'Conseils Pro',
    keyTakeaways: 'Points Clés',
    loading: 'Chargement...',
    generating: 'Génération de votre guide...',
    tryAgain: 'Réessayer',
    powered_by: 'Propulsé par',
    introductionTo: 'Introduction à',
    weaving: 'Tissage de votre guide...',
    downloadFreeSample: 'Télécharger Échantillon Gratuit (PDF)',
    unlockFullGuide: 'Débloquer le Guide Artisan Complet',
    puttingItIntoPractice: 'Mise en Pratique',
    saving: 'Enregistrement...',
    saved: 'Enregistré dans votre bibliothèque',
    learnAnything: 'Apprenez tout.',
    beautifulGuides: 'Des guides personnalisés et magnifiques créés rien que pour vous.',
    searchExamples: 'Essayez: "Cuisson du pain au levain" ou "Bases de l\'aquarelle"',
    freeSampleDesc: 'L\'échantillon gratuit comprend la couverture, la table des matières et le chapitre 1. Le guide complet débloque tous les chapitres.',
    fullAccessUnlocked: 'Accès complet débloqué',
    beginReading: 'Commencer la Lecture',
    advancedOptions: 'Options Avancées',
    narrativeVoice: 'VOIX NARRATIVE',
    bookStructure: 'STRUCTURE DU LIVRE',
    focusAreas: 'DOMAINES DE FOCUS',
    // Focus Area Labels
    focus_history: 'Histoire',
    focus_wellness: 'Bien-être',
    focus_nightlife: 'Vie Nocturne',
    focus_art: 'Art & Design',
    focus_luxury: 'Luxe',
    focus_culture: 'Culture Locale',
    focus_nature: 'Nature',
    // Focus Area Tooltips
    tooltip_history: 'Histoires anciennes, sites patrimoniaux et chronologies culturelles',
    tooltip_wellness: 'Spas, retraites, méditation et rituels de bien-être',
    tooltip_nightlife: 'Bars, clubs, musique live et scènes nocturnes',
    tooltip_art: 'Galeries, architecture, studios et espaces créatifs',
    tooltip_luxury: 'Expériences haut de gamme, lieux exclusifs et services premium',
    tooltip_culture: 'Traditions, coutumes locales, marchés alimentaires et vie communautaire',
    tooltip_nature: 'Parcs, sentiers de randonnée, plages et aventures en plein air',
    // Voice Labels
    voice_insider: "L'Initié",
    voice_bestie: "L'Ami(e)",
    voice_poet: 'Le Poète',
    voice_professor: 'Le Professeur',
    // Voice Tooltips
    tooltip_insider: 'Sélectionné, cool, "Entre connaisseurs"',
    tooltip_bestie: 'Impertinent, confiant et spirituel',
    tooltip_poet: 'Rêveur, fleuri et romantique',
    tooltip_professor: 'Académique, éducatif et clair',
    // Structure Labels
    structure_curated: 'Guide Sélectionné',
    structure_playbook: 'Manuel Pratique',
    structure_balanced: 'Équilibré',
    // Structure Tooltips
    tooltip_curated: 'Focus: Lieux, Hôtels, Restaurants, Shopping',
    tooltip_playbook: 'Focus: Pratiques, Tutoriels, Rituels, Éducation',
    tooltip_balanced: 'Un mélange 50/50 d\'Enseignement et de Destinations',
    // Weaving Steps
    weaving_step1: 'Rassemblement des fils...',
    weaving_step2: 'Installation du métier à tisser...',
    weaving_step3: 'Tissage des chapitres...',
    weaving_step4: 'Ajout des touches finales...',
    weaving_step5: 'Presque prêt...',
    // Chapter Status
    status_reading: 'Lecture',
    status_expand: 'Développer',
    status_drafting: 'Rédaction...',
    status_pending: 'En attente',
    status_locked: 'Verrouillé',
    chapters: 'Chapitres',
    contents: 'Contenu',
    // Block Labels
    keyTakeaway: 'POINT CLÉ',
    proTip: 'CONSEIL PRO',
    // Download/Progress
    downloadFullGuide: 'Télécharger le Guide Complet (PDF)',
    generatingPdf: 'Génération du PDF...',
    weavingPages: 'Tissage... {count} pages',
    pleaseWaitChapters: 'Veuillez patienter pour tous les chapitres...',
    artisanWeaving: 'Notre Artisan tisse vos détails personnalisés...',
    // Navigation
    prev: 'Préc',
    next: 'Suiv',
    pageTools: 'Outils',
    fit: 'Ajuster',
    fullSize: '100%',
    pageOf: 'sur',
    chapterOf: 'Chapitre {current} sur {total}',
    // Page Tools Menu
    premiumEditingSuite: "Suite d'Édition Premium",
    insertPageBefore: 'Insérer une Page Avant',
    insertPageAfter: 'Insérer une Page Après',
    searchGallery: 'Rechercher dans la Galerie',
    uploadOwnPhoto: 'Téléverser Votre Photo',
    tryIt: 'Essayez !',
    regenerateChapter: 'Régénérer le Chapitre {n}',
    editPageContent: 'Modifier le Contenu de la Page',
    deleteThisPage: 'Supprimer Cette Page',
    bwPrintMode: 'Mode Impression N&B',
    bwPrintModeDesc: "Optimisé pour l'impression N&B moins chère d'Amazon",
    // Image States
    searchingArchives: 'Recherche dans les Archives...',
    searching: 'Recherche...',
    aiSelected: 'Sélectionné par IA',
    imageNotFound: 'Image non trouvée',
    // Cover Studio
    coverStudio: 'Studio de Couverture',
    previewStudio: 'Studio de Prévisualisation',
    kdpCoverStudioTitle: "Studio KDP & Gestionnaire d'Export",
    // Tab Labels
    tabFront: 'Avant',
    tabBack: 'Arrière',
    tabSpine: 'Dos',
    tabWrap: 'Complet',
    tabPrep: 'Prépa',
    tabRoyalty: '$$$',
    tabExport: 'Export',
    // Front Tab
    currentFrontCover: 'Couverture Avant Actuelle',
    editCoverText: 'Modifier le Texte de Couverture',
    viewOnly: 'Lecture Seule',
    titleLabel: 'Titre',
    subtitleLabel: 'Sous-titre',
    saveTextChanges: 'Enregistrer les Modifications',
    uploadYourOwnImage: 'Ou Téléversez Votre Image',
    uploadCustomCoverDesc: 'Téléversez une image de couverture personnalisée (JPG, PNG, max 5Mo)',
    uploadCoverImage: 'Téléverser une Image',
    customCoverImage: 'Image de Couverture Personnalisée',
    unlockCoverEditing: 'Débloquer Édition de Couverture',
    coverBranding: 'Image de Marque',
    brand: 'Marque',
    logo: 'Logo',
    uploadLogo: 'Téléverser le Logo',
    changeLogo: 'Changer le Logo',
    reset: 'Réinitialiser',
    premium: 'Premium',
    noImage: 'Aucune Image',
    uploading: 'Téléversement...',
    // Back Tab
    currentBackCover: 'Quatrième de Couverture Actuelle',
    backCoverText: 'Texte de Quatrième de Couverture',
    header: 'En-tête',
    // Export Tab
    completeKdpPackage: 'Package KDP Complet',
    kdpPackageDesc: 'Téléchargez tout ce dont vous avez besoin pour Amazon KDP dans un fichier ZIP :',
    coverFile: 'Couverture complète avec dos',
    manuscriptFile: 'Texte intérieur avec table des matières et images',
    kindleEbook: 'Format eBook Kindle',
    kindleCover: 'Image de couverture eBook',
    downloadKdpPackage: 'Télécharger le Package KDP',
    generatingPackage: 'Génération...',
    // Locked Tab Content
    amazonListingPrep: 'Préparation de Fiche Amazon',
    amazonListingPrepDesc: 'Débloquez pour auto-générer votre Description et Mots-Clés Best-Seller avec IA.',
    royaltyCalculator: 'Calculateur de Royalties',
    royaltyCalculatorDesc: 'Débloquez pour calculer vos royalties KDP et optimiser votre stratégie de prix.',
    // Prep Dashboard
    preparingMetadata: 'Préparation des métadonnées Amazon...',
    generatingMetadata: 'Génération de la description, du sous-titre et des mots-clés...',
    pageCount: 'Nombre de Pages',
    spineLabel: 'Dos',
    trimLabel: 'Format',
    bleedLabel: 'Fond Perdu',
    bookDescription: 'Description du Livre',
    preview: 'Aperçu',
    html: 'HTML',
    previewFormatted: 'Aperçu (Formaté)',
    editHtml: 'Éditer HTML',
    writeBestSellingDesc: 'Rédiger une Description Best-Seller',
    copyHtmlNote: "L'aperçu affiche le texte formaté. Le bouton copier copie le HTML brut pour Amazon KDP.",
    authorLabel: 'Auteur',
    generateSubtitle: 'Générer sous-titre',
    keywords: 'Mots-Clés',
    generateAll: 'Générer Tout',
    keywordsNote: 'Les mots-clés évitent de répéter les mots de votre titre pour un meilleur classement Amazon.',
    // Footer
    aiDisclaimer: "Contenu généré par IA pour inspiration créative uniquement. Ce n'est pas un conseil professionnel.",
  },
  de: {
    join: 'Beitreten',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    search: 'Suchen',
    searchPlaceholder: 'Was möchten Sie heute lernen?',
    whereToStay: 'Unterkunft',
    theVibe: 'Die Atmosphäre',
    downloadPDF: 'PDF Herunterladen',
    aCuratedGuide: 'Ein Kuratierter Leitfaden',
    printPreview: 'Druckvorschau',
    newGuide: 'Neuer Leitfaden',
    dashboard: 'Dashboard',
    myProjects: 'Meine Projekte',
    saveToLibrary: 'Speichern',
    localResources: 'Lokale Ressourcen',
    enableLocation: 'Standort Aktivieren',
    chapterOne: 'Kapitel Eins',
    chapterTwo: 'Kapitel Zwei',
    chapterThree: 'Kapitel Drei',
    tableOfContents: 'Inhaltsverzeichnis',
    commonMistakes: 'Häufige Fehler',
    proTips: 'Profi-Tipps',
    keyTakeaways: 'Wichtigste Erkenntnisse',
    loading: 'Laden...',
    generating: 'Ihr Leitfaden wird erstellt...',
    tryAgain: 'Erneut Versuchen',
    powered_by: 'Unterstützt von',
    introductionTo: 'Einführung in',
    weaving: 'Weben Ihres Leitfadens...',
    downloadFreeSample: 'Kostenlose Probe Herunterladen (PDF)',
    unlockFullGuide: 'Vollständigen Handwerker-Leitfaden Freischalten',
    puttingItIntoPractice: 'In die Praxis Umsetzen',
    saving: 'Speichern...',
    saved: 'In Ihrer Bibliothek gespeichert',
    learnAnything: 'Lernen Sie alles.',
    beautifulGuides: 'Schöne, individuelle Anleitungen, die nur für Sie erstellt wurden.',
    searchExamples: 'Versuchen Sie: "Sauerteigbrot backen" oder "Aquarell-Grundlagen"',
    freeSampleDesc: 'Die kostenlose Probe enthält das Cover, das Inhaltsverzeichnis und Kapitel 1. Der vollständige Leitfaden schaltet alle Kapitel frei.',
    fullAccessUnlocked: 'Vollzugriff freigeschaltet',
    beginReading: 'Mit dem Lesen beginnen',
    advancedOptions: 'Erweiterte Optionen',
    narrativeVoice: 'ERZÄHLSTIMME',
    bookStructure: 'BUCHSTRUKTUR',
    focusAreas: 'SCHWERPUNKTE',
    // Focus Area Labels
    focus_history: 'Geschichte',
    focus_wellness: 'Wellness',
    focus_nightlife: 'Nachtleben',
    focus_art: 'Kunst & Design',
    focus_luxury: 'Luxus',
    focus_culture: 'Lokale Kultur',
    focus_nature: 'Natur',
    // Focus Area Tooltips
    tooltip_history: 'Alte Geschichten, Kulturerbestätten und kulturelle Zeitleisten',
    tooltip_wellness: 'Spas, Retreats, Meditation und Selbstpflege-Rituale',
    tooltip_nightlife: 'Bars, Clubs, Live-Musik und Nachtleben',
    tooltip_art: 'Galerien, Architektur, Studios und kreative Räume',
    tooltip_luxury: 'High-End-Erlebnisse, exklusive Orte und Premium-Services',
    tooltip_culture: 'Traditionen, lokale Bräuche, Lebensmittelmärkte und Gemeinschaftsleben',
    tooltip_nature: 'Parks, Wanderwege, Strände und Outdoor-Abenteuer',
    // Voice Labels
    voice_insider: 'Der Insider',
    voice_bestie: 'Der/Die Freund/in',
    voice_poet: 'Der Dichter',
    voice_professor: 'Der Professor',
    // Voice Tooltips
    tooltip_insider: 'Kuratiert, cool, "Wenn du es weißt, weißt du es"',
    tooltip_bestie: 'Frech, selbstbewusst und witzig',
    tooltip_poet: 'Verträumt, blumig und romantisch',
    tooltip_professor: 'Akademisch, lehrreich und klar',
    // Structure Labels
    structure_curated: 'Kuratierter Leitfaden',
    structure_playbook: 'Handbuch',
    structure_balanced: 'Ausgewogen',
    // Structure Tooltips
    tooltip_curated: 'Fokus: Orte, Hotels, Restaurants, Shopping',
    tooltip_playbook: 'Fokus: Praktiken, Anleitungen, Rituale, Bildung',
    tooltip_balanced: 'Eine 50/50 Mischung aus Lehre und Reisezielen',
    // Weaving Steps
    weaving_step1: 'Fäden sammeln...',
    weaving_step2: 'Webstuhl aufstellen...',
    weaving_step3: 'Kapitel weben...',
    weaving_step4: 'Letzte Details hinzufügen...',
    weaving_step5: 'Fast fertig...',
    // Chapter Status
    status_reading: 'Lesen',
    status_expand: 'Erweitern',
    status_drafting: 'Entwurf...',
    status_pending: 'Ausstehend',
    status_locked: 'Gesperrt',
    chapters: 'Kapitel',
    contents: 'Inhalt',
    // Block Labels
    keyTakeaway: 'WICHTIGSTE ERKENNTNIS',
    proTip: 'PROFI-TIPP',
    // Download/Progress
    downloadFullGuide: 'Vollständigen Leitfaden Herunterladen (PDF)',
    generatingPdf: 'PDF wird erstellt...',
    weavingPages: 'Weben... {count} Seiten',
    pleaseWaitChapters: 'Bitte warten Sie auf alle Kapitel...',
    artisanWeaving: 'Unser Handwerker webt Ihre individuellen Details...',
    // Navigation
    prev: 'Zurück',
    next: 'Weiter',
    pageTools: 'Werkzeuge',
    fit: 'Anpassen',
    fullSize: '100%',
    pageOf: 'von',
    chapterOf: 'Kapitel {current} von {total}',
    // Page Tools Menu
    premiumEditingSuite: 'Premium-Bearbeitungssuite',
    insertPageBefore: 'Seite Davor Einfügen',
    insertPageAfter: 'Seite Danach Einfügen',
    searchGallery: 'Galerie Durchsuchen',
    uploadOwnPhoto: 'Eigenes Foto Hochladen',
    tryIt: 'Probieren!',
    regenerateChapter: 'Kapitel {n} Regenerieren',
    editPageContent: 'Seiteninhalt Bearbeiten',
    deleteThisPage: 'Diese Seite Löschen',
    bwPrintMode: 'S&W-Druckmodus',
    bwPrintModeDesc: 'Optimiert für Amazons günstigeren S&W-Druck',
    // Image States
    searchingArchives: 'Durchsuche Archive...',
    searching: 'Suche...',
    aiSelected: 'KI-ausgewählt',
    imageNotFound: 'Bild nicht gefunden',
    // Cover Studio
    coverStudio: 'Cover-Studio',
    previewStudio: 'Vorschau-Studio',
    kdpCoverStudioTitle: 'KDP Cover-Studio & Export-Manager',
    // Tab Labels
    tabFront: 'Vorne',
    tabBack: 'Hinten',
    tabSpine: 'Buchrücken',
    tabWrap: 'Komplett',
    tabPrep: 'Vorbereitung',
    tabRoyalty: '$$$',
    tabExport: 'Export',
    // Front Tab
    currentFrontCover: 'Aktuelles Frontcover',
    editCoverText: 'Cover-Text Bearbeiten',
    viewOnly: 'Nur Ansicht',
    titleLabel: 'Titel',
    subtitleLabel: 'Untertitel',
    saveTextChanges: 'Textänderungen Speichern',
    uploadYourOwnImage: 'Oder Eigenes Bild Hochladen',
    uploadCustomCoverDesc: 'Laden Sie ein benutzerdefiniertes Cover-Bild hoch (JPG, PNG, max 5MB)',
    uploadCoverImage: 'Cover-Bild Hochladen',
    customCoverImage: 'Benutzerdefiniertes Cover-Bild',
    unlockCoverEditing: 'Cover-Bearbeitung Freischalten',
    coverBranding: 'Cover-Branding',
    brand: 'Marke',
    logo: 'Logo',
    uploadLogo: 'Logo Hochladen',
    changeLogo: 'Logo Ändern',
    reset: 'Zurücksetzen',
    premium: 'Premium',
    noImage: 'Kein Bild',
    uploading: 'Hochladen...',
    // Back Tab
    currentBackCover: 'Aktuelles Rückcover',
    backCoverText: 'Rückcover-Text',
    header: 'Überschrift',
    // Export Tab
    completeKdpPackage: 'Komplettes KDP-Paket',
    kdpPackageDesc: 'Laden Sie alles herunter, was Sie für Amazon KDP benötigen, in einer ZIP-Datei:',
    coverFile: 'Vollständiges Cover mit Buchrücken',
    manuscriptFile: 'Innentext mit Inhaltsverzeichnis & Bildern',
    kindleEbook: 'Kindle eBook-Format',
    kindleCover: 'eBook-Cover-Bild',
    downloadKdpPackage: 'KDP-Paket Herunterladen',
    generatingPackage: 'Wird generiert...',
    // Locked Tab Content
    amazonListingPrep: 'Amazon-Listenvorbereitung',
    amazonListingPrepDesc: 'Freischalten um Ihre Best-Seller-Beschreibung und Keywords mit KI automatisch zu generieren.',
    royaltyCalculator: 'Lizenzgebühren-Rechner',
    royaltyCalculatorDesc: 'Freischalten um Ihre KDP-Lizenzgebühren zu berechnen und Ihre Preisstrategie zu optimieren.',
    // Prep Dashboard
    preparingMetadata: 'Amazon-Metadaten werden vorbereitet...',
    generatingMetadata: 'Beschreibung, Untertitel und Keywords werden generiert...',
    pageCount: 'Seitenzahl',
    spineLabel: 'Buchrücken',
    trimLabel: 'Beschnitt',
    bleedLabel: 'Anschnitt',
    bookDescription: 'Buchbeschreibung',
    preview: 'Vorschau',
    html: 'HTML',
    previewFormatted: 'Vorschau (Formatiert)',
    editHtml: 'HTML Bearbeiten',
    writeBestSellingDesc: 'Best-Seller-Beschreibung Schreiben',
    copyHtmlNote: 'Vorschau zeigt formatierten Text. Kopieren-Button kopiert rohes HTML für Amazon KDP.',
    authorLabel: 'Autor',
    generateSubtitle: 'Untertitel generieren',
    keywords: 'Schlüsselwörter',
    generateAll: 'Alle Generieren',
    keywordsNote: 'Schlüsselwörter vermeiden Wörter aus Ihrem Titel für besseres Amazon-Ranking.',
    // Footer
    aiDisclaimer: 'KI-generierter Inhalt nur zur kreativen Inspiration. Kein professioneller Rat.',
  },
  it: {
    join: 'Unisciti',
    signIn: 'Accedi',
    signOut: 'Esci',
    search: 'Cerca',
    searchPlaceholder: 'Cosa vuoi imparare oggi?',
    whereToStay: 'Dove Alloggiare',
    theVibe: "L'Atmosfera",
    downloadPDF: 'Scarica PDF',
    aCuratedGuide: 'Una Guida Curata',
    printPreview: 'Anteprima di Stampa',
    newGuide: 'Nuova Guida',
    dashboard: 'Dashboard',
    myProjects: 'I Miei Progetti',
    saveToLibrary: 'Salva in Libreria',
    localResources: 'Risorse Locali',
    enableLocation: 'Attiva Posizione',
    chapterOne: 'Capitolo Uno',
    chapterTwo: 'Capitolo Due',
    chapterThree: 'Capitolo Tre',
    tableOfContents: 'Indice',
    commonMistakes: 'Errori Comuni',
    proTips: 'Consigli Pro',
    keyTakeaways: 'Punti Chiave',
    loading: 'Caricamento...',
    generating: 'Generazione della tua guida...',
    tryAgain: 'Riprova',
    powered_by: 'Alimentato da',
    introductionTo: 'Introduzione a',
    weaving: 'Tessendo la tua guida...',
    downloadFreeSample: 'Scarica Campione Gratuito (PDF)',
    unlockFullGuide: 'Sblocca la Guida Artigianale Completa',
    puttingItIntoPractice: 'Metterlo in Pratica',
    saving: 'Salvataggio...',
    saved: 'Salvato nella tua libreria',
    learnAnything: 'Impara qualsiasi cosa.',
    beautifulGuides: 'Guide personalizzate e belle create solo per te.',
    searchExamples: 'Prova: "Fare il pane con lievito madre" o "Basi dell\'acquerello"',
    freeSampleDesc: 'Il campione gratuito include la copertina, l\'indice e il capitolo 1. La guida completa sblocca tutti i capitoli.',
    fullAccessUnlocked: 'Accesso completo sbloccato',
    beginReading: 'Inizia a Leggere',
    advancedOptions: 'Opzioni Avanzate',
    narrativeVoice: 'VOCE NARRATIVA',
    bookStructure: 'STRUTTURA DEL LIBRO',
    focusAreas: 'AREE DI FOCUS',
    // Focus Area Labels
    focus_history: 'Storia',
    focus_wellness: 'Benessere',
    focus_nightlife: 'Vita Notturna',
    focus_art: 'Arte & Design',
    focus_luxury: 'Lusso',
    focus_culture: 'Cultura Locale',
    focus_nature: 'Natura',
    // Focus Area Tooltips
    tooltip_history: 'Storie antiche, siti del patrimonio e cronologie culturali',
    tooltip_wellness: 'Spa, ritiri, meditazione e rituali di cura di sé',
    tooltip_nightlife: 'Bar, club, musica dal vivo e scene notturne',
    tooltip_art: 'Gallerie, architettura, studi e spazi creativi',
    tooltip_luxury: 'Esperienze di alto livello, luoghi esclusivi e servizi premium',
    tooltip_culture: 'Tradizioni, usanze locali, mercati alimentari e vita comunitaria',
    tooltip_nature: 'Parchi, sentieri, spiagge e avventure all\'aperto',
    // Voice Labels
    voice_insider: "L'Iniziato",
    voice_bestie: "L'Amico/a",
    voice_poet: 'Il Poeta',
    voice_professor: 'Il Professore',
    // Voice Tooltips
    tooltip_insider: 'Curato, cool, "Se lo sai, lo sai"',
    tooltip_bestie: 'Sfacciato, sicuro e spiritoso',
    tooltip_poet: 'Sognante, fiorito e romantico',
    tooltip_professor: 'Accademico, educativo e chiaro',
    // Structure Labels
    structure_curated: 'Guida Curata',
    structure_playbook: 'Manuale',
    structure_balanced: 'Equilibrato',
    // Structure Tooltips
    tooltip_curated: 'Focus: Luoghi, Hotel, Ristoranti, Shopping',
    tooltip_playbook: 'Focus: Pratiche, Tutorial, Rituali, Educazione',
    tooltip_balanced: 'Un mix 50/50 di Insegnamento e Destinazioni',
    // Weaving Steps
    weaving_step1: 'Raccogliendo i fili...',
    weaving_step2: 'Preparando il telaio...',
    weaving_step3: 'Tessendo i capitoli...',
    weaving_step4: 'Aggiungendo i tocchi finali...',
    weaving_step5: 'Quasi pronto...',
    // Chapter Status
    status_reading: 'Lettura',
    status_expand: 'Espandi',
    status_drafting: 'Bozza...',
    status_pending: 'In attesa',
    status_locked: 'Bloccato',
    chapters: 'Capitoli',
    contents: 'Contenuto',
    // Block Labels
    keyTakeaway: 'PUNTO CHIAVE',
    proTip: 'CONSIGLIO PRO',
    // Download/Progress
    downloadFullGuide: 'Scarica Guida Completa (PDF)',
    generatingPdf: 'Generazione PDF...',
    weavingPages: 'Tessendo... {count} pagine',
    pleaseWaitChapters: 'Attendi tutti i capitoli...',
    artisanWeaving: 'Il nostro Artigiano sta tessendo i tuoi dettagli personalizzati...',
    // Navigation
    prev: 'Prec',
    next: 'Succ',
    pageTools: 'Strumenti',
    fit: 'Adatta',
    fullSize: '100%',
    pageOf: 'di',
    chapterOf: 'Capitolo {current} di {total}',
    // Page Tools Menu
    premiumEditingSuite: 'Suite di Modifica Premium',
    insertPageBefore: 'Inserisci Pagina Prima',
    insertPageAfter: 'Inserisci Pagina Dopo',
    searchGallery: 'Cerca nella Galleria',
    uploadOwnPhoto: 'Carica la Tua Foto',
    tryIt: 'Provalo!',
    regenerateChapter: 'Rigenera Capitolo {n}',
    editPageContent: 'Modifica Contenuto Pagina',
    deleteThisPage: 'Elimina Questa Pagina',
    bwPrintMode: 'Modalità Stampa B&N',
    bwPrintModeDesc: 'Ottimizza per la stampa B&N più economica di Amazon',
    // Image States
    searchingArchives: 'Ricerca negli Archivi...',
    searching: 'Ricerca...',
    aiSelected: 'Selezionato da IA',
    imageNotFound: 'Immagine non trovata',
    // Cover Studio
    coverStudio: 'Studio Copertina',
    previewStudio: 'Studio Anteprima',
    kdpCoverStudioTitle: 'Studio Copertina KDP & Gestore Esportazione',
    // Tab Labels
    tabFront: 'Fronte',
    tabBack: 'Retro',
    tabSpine: 'Dorso',
    tabWrap: 'Completo',
    tabPrep: 'Prep',
    tabRoyalty: '$$$',
    tabExport: 'Esporta',
    // Front Tab
    currentFrontCover: 'Copertina Fronte Attuale',
    editCoverText: 'Modifica Testo Copertina',
    viewOnly: 'Solo Visualizzazione',
    titleLabel: 'Titolo',
    subtitleLabel: 'Sottotitolo',
    saveTextChanges: 'Salva Modifiche Testo',
    uploadYourOwnImage: 'O Carica la Tua Immagine',
    uploadCustomCoverDesc: 'Carica un\'immagine di copertina personalizzata (JPG, PNG, max 5MB)',
    uploadCoverImage: 'Carica Immagine Copertina',
    customCoverImage: 'Immagine Copertina Personalizzata',
    unlockCoverEditing: 'Sblocca Modifica Copertina',
    coverBranding: 'Branding Copertina',
    brand: 'Marchio',
    logo: 'Logo',
    uploadLogo: 'Carica Logo',
    changeLogo: 'Cambia Logo',
    reset: 'Ripristina',
    premium: 'Premium',
    noImage: 'Nessuna Immagine',
    uploading: 'Caricamento...',
    // Back Tab
    currentBackCover: 'Quarta di Copertina Attuale',
    backCoverText: 'Testo Quarta di Copertina',
    header: 'Intestazione',
    // Export Tab
    completeKdpPackage: 'Pacchetto KDP Completo',
    kdpPackageDesc: 'Scarica tutto ciò di cui hai bisogno per Amazon KDP in un file ZIP:',
    coverFile: 'Copertina completa con dorso',
    manuscriptFile: 'Testo interno con indice e immagini',
    kindleEbook: 'Formato eBook Kindle',
    kindleCover: 'Immagine copertina eBook',
    downloadKdpPackage: 'Scarica Pacchetto KDP',
    generatingPackage: 'Generazione...',
    // Locked Tab Content
    amazonListingPrep: 'Preparazione Inserzione Amazon',
    amazonListingPrepDesc: 'Sblocca per auto-generare la tua Descrizione e Parole Chiave Best-Seller con IA.',
    royaltyCalculator: 'Calcolatore Royalty',
    royaltyCalculatorDesc: 'Sblocca per calcolare le tue royalty KDP e ottimizzare la tua strategia di prezzo.',
    // Prep Dashboard
    preparingMetadata: 'Preparazione metadati Amazon...',
    generatingMetadata: 'Generazione descrizione, sottotitolo e parole chiave...',
    pageCount: 'Numero Pagine',
    spineLabel: 'Dorso',
    trimLabel: 'Formato',
    bleedLabel: 'Abbondanza',
    bookDescription: 'Descrizione Libro',
    preview: 'Anteprima',
    html: 'HTML',
    previewFormatted: 'Anteprima (Formattata)',
    editHtml: 'Modifica HTML',
    writeBestSellingDesc: 'Scrivi Descrizione Best-Seller',
    copyHtmlNote: 'L\'anteprima mostra testo formattato. Il pulsante copia copia HTML grezzo per Amazon KDP.',
    authorLabel: 'Autore',
    generateSubtitle: 'Genera sottotitolo',
    keywords: 'Parole Chiave',
    generateAll: 'Genera Tutto',
    keywordsNote: 'Le parole chiave evitano di ripetere parole dal tuo titolo per un migliore ranking Amazon.',
    // Footer
    aiDisclaimer: 'Contenuto generato da IA solo per ispirazione creativa. Non è un consiglio professionale.',
  },
  pt: {
    join: 'Junte-se',
    signIn: 'Entrar',
    signOut: 'Sair',
    search: 'Pesquisar',
    searchPlaceholder: 'O que você quer aprender hoje?',
    whereToStay: 'Onde Ficar',
    theVibe: 'A Vibe',
    downloadPDF: 'Baixar PDF',
    aCuratedGuide: 'Um Guia Curado',
    printPreview: 'Visualizar Impressão',
    newGuide: 'Novo Guia',
    dashboard: 'Painel',
    myProjects: 'Meus Projetos',
    saveToLibrary: 'Salvar na Biblioteca',
    localResources: 'Recursos Locais',
    enableLocation: 'Ativar Localização',
    chapterOne: 'Capítulo Um',
    chapterTwo: 'Capítulo Dois',
    chapterThree: 'Capítulo Três',
    tableOfContents: 'Índice',
    commonMistakes: 'Erros Comuns',
    proTips: 'Dicas Pro',
    keyTakeaways: 'Pontos-Chave',
    loading: 'Carregando...',
    generating: 'Gerando seu guia...',
    tryAgain: 'Tentar Novamente',
    powered_by: 'Desenvolvido por',
    introductionTo: 'Introdução a',
    weaving: 'Tecendo seu guia...',
    downloadFreeSample: 'Baixar Amostra Grátis (PDF)',
    unlockFullGuide: 'Desbloquear Guia Artesanal Completo',
    puttingItIntoPractice: 'Colocando em Prática',
    saving: 'Salvando...',
    saved: 'Salvo na sua biblioteca',
    learnAnything: 'Aprenda qualquer coisa.',
    beautifulGuides: 'Guias personalizados e bonitos criados só para você.',
    searchExamples: 'Tente: "Fazer pão de fermentação natural" ou "Básico de aquarela"',
    freeSampleDesc: 'A amostra grátis inclui a capa, o índice e o capítulo 1. O guia completo desbloqueia todos os capítulos.',
    fullAccessUnlocked: 'Acesso completo desbloqueado',
    beginReading: 'Começar a Ler',
    advancedOptions: 'Opções Avançadas',
    narrativeVoice: 'VOZ NARRATIVA',
    bookStructure: 'ESTRUTURA DO LIVRO',
    focusAreas: 'ÁREAS DE FOCO',
    // Focus Area Labels
    focus_history: 'História',
    focus_wellness: 'Bem-estar',
    focus_nightlife: 'Vida Noturna',
    focus_art: 'Arte & Design',
    focus_luxury: 'Luxo',
    focus_culture: 'Cultura Local',
    focus_nature: 'Natureza',
    // Focus Area Tooltips
    tooltip_history: 'Histórias antigas, patrimônios culturais e cronologias',
    tooltip_wellness: 'Spas, retiros, meditação e rituais de autocuidado',
    tooltip_nightlife: 'Bares, clubes, música ao vivo e cenas noturnas',
    tooltip_art: 'Galerias, arquitetura, estúdios e espaços criativos',
    tooltip_luxury: 'Experiências de alto padrão, locais exclusivos e serviços premium',
    tooltip_culture: 'Tradições, costumes locais, mercados e vida comunitária',
    tooltip_nature: 'Parques, trilhas, praias e aventuras ao ar livre',
    // Voice Labels
    voice_insider: 'O Iniciado',
    voice_bestie: 'O/A Amigo/a',
    voice_poet: 'O Poeta',
    voice_professor: 'O Professor',
    // Voice Tooltips
    tooltip_insider: 'Curado, legal, "Se você sabe, você sabe"',
    tooltip_bestie: 'Atrevido, confiante e espirituoso',
    tooltip_poet: 'Sonhador, florido e romântico',
    tooltip_professor: 'Acadêmico, educacional e claro',
    // Structure Labels
    structure_curated: 'Guia Curado',
    structure_playbook: 'Manual',
    structure_balanced: 'Equilibrado',
    // Structure Tooltips
    tooltip_curated: 'Foco: Lugares, Hotéis, Restaurantes, Compras',
    tooltip_playbook: 'Foco: Práticas, Tutoriais, Rituais, Educação',
    tooltip_balanced: 'Uma mistura 50/50 de Ensino e Destinos',
    // Weaving Steps
    weaving_step1: 'Reunindo fios...',
    weaving_step2: 'Preparando o tear...',
    weaving_step3: 'Tecendo capítulos...',
    weaving_step4: 'Adicionando toques finais...',
    weaving_step5: 'Quase pronto...',
    // Chapter Status
    status_reading: 'Lendo',
    status_expand: 'Expandir',
    status_drafting: 'Redigindo...',
    status_pending: 'Pendente',
    status_locked: 'Bloqueado',
    chapters: 'Capítulos',
    contents: 'Conteúdo',
    // Block Labels
    keyTakeaway: 'PONTO-CHAVE',
    proTip: 'DICA PRO',
    // Download/Progress
    downloadFullGuide: 'Baixar Guia Completo (PDF)',
    generatingPdf: 'Gerando PDF...',
    weavingPages: 'Tecendo... {count} páginas',
    pleaseWaitChapters: 'Por favor aguarde todos os capítulos...',
    artisanWeaving: 'Nosso Artesão está tecendo seus detalhes personalizados...',
    // Navigation
    prev: 'Ant',
    next: 'Próx',
    pageTools: 'Ferramentas',
    fit: 'Ajustar',
    fullSize: '100%',
    pageOf: 'de',
    chapterOf: 'Capítulo {current} de {total}',
    // Page Tools Menu
    premiumEditingSuite: 'Suite de Edição Premium',
    insertPageBefore: 'Inserir Página Antes',
    insertPageAfter: 'Inserir Página Depois',
    searchGallery: 'Pesquisar na Galeria',
    uploadOwnPhoto: 'Carregar Sua Foto',
    tryIt: 'Experimente!',
    regenerateChapter: 'Regenerar Capítulo {n}',
    editPageContent: 'Editar Conteúdo da Página',
    deleteThisPage: 'Excluir Esta Página',
    bwPrintMode: 'Modo Impressão P&B',
    bwPrintModeDesc: 'Otimiza para a impressão P&B mais barata da Amazon',
    // Image States
    searchingArchives: 'Pesquisando nos Arquivos...',
    searching: 'Pesquisando...',
    aiSelected: 'Selecionado por IA',
    imageNotFound: 'Imagem não encontrada',
    // Cover Studio
    coverStudio: 'Estúdio de Capa',
    previewStudio: 'Estúdio de Pré-visualização',
    kdpCoverStudioTitle: 'Estúdio de Capa KDP & Gerenciador de Exportação',
    // Tab Labels
    tabFront: 'Frente',
    tabBack: 'Verso',
    tabSpine: 'Lombada',
    tabWrap: 'Completo',
    tabPrep: 'Prep',
    tabRoyalty: '$$$',
    tabExport: 'Exportar',
    // Front Tab
    currentFrontCover: 'Capa Frontal Atual',
    editCoverText: 'Editar Texto da Capa',
    viewOnly: 'Apenas Visualização',
    titleLabel: 'Título',
    subtitleLabel: 'Subtítulo',
    saveTextChanges: 'Salvar Alterações de Texto',
    uploadYourOwnImage: 'Ou Carregue Sua Imagem',
    uploadCustomCoverDesc: 'Carregue uma imagem de capa personalizada (JPG, PNG, máx 5MB)',
    uploadCoverImage: 'Carregar Imagem de Capa',
    customCoverImage: 'Imagem de Capa Personalizada',
    unlockCoverEditing: 'Desbloquear Edição de Capa',
    coverBranding: 'Branding de Capa',
    brand: 'Marca',
    logo: 'Logo',
    uploadLogo: 'Carregar Logo',
    changeLogo: 'Alterar Logo',
    reset: 'Redefinir',
    premium: 'Premium',
    noImage: 'Sem Imagem',
    uploading: 'Carregando...',
    // Back Tab
    currentBackCover: 'Contracapa Atual',
    backCoverText: 'Texto da Contracapa',
    header: 'Cabeçalho',
    // Export Tab
    completeKdpPackage: 'Pacote KDP Completo',
    kdpPackageDesc: 'Baixe tudo o que você precisa para Amazon KDP em um arquivo ZIP:',
    coverFile: 'Capa completa com lombada',
    manuscriptFile: 'Texto interno com sumário e imagens',
    kindleEbook: 'Formato eBook Kindle',
    kindleCover: 'Imagem de capa eBook',
    downloadKdpPackage: 'Baixar Pacote KDP',
    generatingPackage: 'Gerando...',
    // Locked Tab Content
    amazonListingPrep: 'Preparação de Listagem Amazon',
    amazonListingPrepDesc: 'Desbloqueie para auto-gerar sua Descrição e Palavras-Chave Best-Seller com IA.',
    royaltyCalculator: 'Calculadora de Royalties',
    royaltyCalculatorDesc: 'Desbloqueie para calcular seus royalties KDP e otimizar sua estratégia de preços.',
    // Prep Dashboard
    preparingMetadata: 'Preparando metadados da Amazon...',
    generatingMetadata: 'Gerando descrição, subtítulo e palavras-chave...',
    pageCount: 'Contagem de Páginas',
    spineLabel: 'Lombada',
    trimLabel: 'Formato',
    bleedLabel: 'Sangria',
    bookDescription: 'Descrição do Livro',
    preview: 'Pré-visualização',
    html: 'HTML',
    previewFormatted: 'Pré-visualização (Formatada)',
    editHtml: 'Editar HTML',
    writeBestSellingDesc: 'Escrever Descrição Best-Seller',
    copyHtmlNote: 'A pré-visualização mostra texto formatado. O botão copiar copia HTML bruto para Amazon KDP.',
    authorLabel: 'Autor',
    generateSubtitle: 'Gerar subtítulo',
    keywords: 'Palavras-Chave',
    generateAll: 'Gerar Tudo',
    keywordsNote: 'Palavras-chave evitam repetir palavras do seu título para melhor ranking na Amazon.',
    // Footer
    aiDisclaimer: 'Conteúdo gerado por IA apenas para inspiração criativa. Não é aconselhamento profissional.',
  },
  zh: {
    join: '加入',
    signIn: '登录',
    signOut: '退出',
    search: '搜索',
    searchPlaceholder: '今天想学什么？',
    whereToStay: '住宿推荐',
    theVibe: '氛围',
    downloadPDF: '下载PDF',
    aCuratedGuide: '精选指南',
    printPreview: '打印预览',
    newGuide: '新指南',
    dashboard: '控制面板',
    myProjects: '我的项目',
    saveToLibrary: '保存到书库',
    localResources: '本地资源',
    enableLocation: '启用定位',
    chapterOne: '第一章',
    chapterTwo: '第二章',
    chapterThree: '第三章',
    tableOfContents: '目录',
    commonMistakes: '常见错误',
    proTips: '专业提示',
    keyTakeaways: '关键要点',
    loading: '加载中...',
    generating: '正在生成您的指南...',
    tryAgain: '重试',
    powered_by: '技术支持',
    introductionTo: '简介',
    weaving: '正在编织您的指南...',
    downloadFreeSample: '下载免费样本 (PDF)',
    unlockFullGuide: '解锁完整工匠指南',
    puttingItIntoPractice: '付诸实践',
    saving: '保存中...',
    saved: '已保存到您的书库',
    learnAnything: '学习任何东西。',
    beautifulGuides: '专为您打造的精美定制指南。',
    searchExamples: '试试："酸面包烘焙"或"水彩画基础"',
    freeSampleDesc: '免费样本包括封面、目录和第1章。完整指南解锁全部章节。',
    fullAccessUnlocked: '已解锁完整访问权限',
    beginReading: '开始阅读',
    advancedOptions: '高级选项',
    narrativeVoice: '叙事风格',
    bookStructure: '书籍结构',
    focusAreas: '关注领域',
    // Focus Area Labels
    focus_history: '历史',
    focus_wellness: '养生',
    focus_nightlife: '夜生活',
    focus_art: '艺术设计',
    focus_luxury: '奢华',
    focus_culture: '当地文化',
    focus_nature: '自然',
    // Focus Area Tooltips
    tooltip_history: '古老故事、文化遗产和历史时间线',
    tooltip_wellness: '水疗、静修、冥想和自我护理仪式',
    tooltip_nightlife: '酒吧、俱乐部、现场音乐和夜生活',
    tooltip_art: '画廊、建筑、工作室和创意空间',
    tooltip_luxury: '高端体验、专属场所和优质服务',
    tooltip_culture: '传统、当地习俗、美食市场和社区生活',
    tooltip_nature: '公园、徒步小径、海滩和户外冒险',
    // Voice Labels
    voice_insider: '内行人',
    voice_bestie: '闺蜜',
    voice_poet: '诗人',
    voice_professor: '教授',
    // Voice Tooltips
    tooltip_insider: '精选、时尚、"懂的都懂"',
    tooltip_bestie: '俏皮、自信、机智',
    tooltip_poet: '梦幻、浪漫、诗意',
    tooltip_professor: '学术、教育、清晰',
    // Structure Labels
    structure_curated: '精选指南',
    structure_playbook: '实用手册',
    structure_balanced: '均衡',
    // Structure Tooltips
    tooltip_curated: '重点：地点、酒店、餐厅、购物',
    tooltip_playbook: '重点：实践、教程、仪式、教育',
    tooltip_balanced: '教学与目的地的50/50混合',
    // Weaving Steps
    weaving_step1: '收集丝线...',
    weaving_step2: '准备织布机...',
    weaving_step3: '编织章节...',
    weaving_step4: '添加最后润色...',
    weaving_step5: '即将完成...',
    // Chapter Status
    status_reading: '阅读中',
    status_expand: '展开',
    status_drafting: '草拟中...',
    status_pending: '待处理',
    status_locked: '已锁定',
    chapters: '章节',
    contents: '内容',
    // Block Labels
    keyTakeaway: '关键要点',
    proTip: '专业提示',
    // Download/Progress
    downloadFullGuide: '下载完整指南 (PDF)',
    generatingPdf: '正在生成PDF...',
    weavingPages: '编织中... {count} 页',
    pleaseWaitChapters: '请等待所有章节完成...',
    artisanWeaving: '我们的工匠正在编织您的定制细节...',
    // Navigation
    prev: '上一页',
    next: '下一页',
    pageTools: '页面工具',
    fit: '适应',
    fullSize: '100%',
    pageOf: '/',
    chapterOf: '第{current}章 共{total}章',
    // Page Tools Menu
    premiumEditingSuite: '高级编辑套件',
    insertPageBefore: '在前面插入页面',
    insertPageAfter: '在后面插入页面',
    searchGallery: '搜索图库',
    uploadOwnPhoto: '上传您的照片',
    tryIt: '试试看！',
    regenerateChapter: '重新生成第{n}章',
    editPageContent: '编辑页面内容',
    deleteThisPage: '删除此页面',
    bwPrintMode: '黑白打印模式',
    bwPrintModeDesc: '优化Amazon更便宜的黑白印刷',
    // Image States
    searchingArchives: '正在搜索档案库...',
    searching: '搜索中...',
    aiSelected: 'AI选择',
    imageNotFound: '未找到图片',
    // Cover Studio
    coverStudio: '封面工作室',
    previewStudio: '预览工作室',
    kdpCoverStudioTitle: 'KDP封面工作室与导出管理器',
    // Tab Labels
    tabFront: '封面',
    tabBack: '封底',
    tabSpine: '书脊',
    tabWrap: '完整',
    tabPrep: '准备',
    tabRoyalty: '$$$',
    tabExport: '导出',
    // Front Tab
    currentFrontCover: '当前封面',
    editCoverText: '编辑封面文字',
    viewOnly: '仅查看',
    titleLabel: '标题',
    subtitleLabel: '副标题',
    saveTextChanges: '保存文字更改',
    uploadYourOwnImage: '或上传您的图片',
    uploadCustomCoverDesc: '上传自定义封面图片（JPG、PNG，最大5MB）',
    uploadCoverImage: '上传封面图片',
    customCoverImage: '自定义封面图片',
    unlockCoverEditing: '解锁封面编辑',
    coverBranding: '封面品牌',
    brand: '品牌',
    logo: '标志',
    uploadLogo: '上传标志',
    changeLogo: '更改标志',
    reset: '重置',
    premium: '高级版',
    noImage: '无图片',
    uploading: '上传中...',
    // Back Tab
    currentBackCover: '当前封底',
    backCoverText: '封底文字',
    header: '标题',
    // Export Tab
    completeKdpPackage: '完整KDP包',
    kdpPackageDesc: '下载Amazon KDP所需的所有内容，打包成一个ZIP文件：',
    coverFile: '带书脊的完整封面',
    manuscriptFile: '带目录和图片的内文',
    kindleEbook: 'Kindle电子书格式',
    kindleCover: '电子书封面图片',
    downloadKdpPackage: '下载KDP包',
    generatingPackage: '生成中...',
    // Locked Tab Content
    amazonListingPrep: 'Amazon商品列表准备',
    amazonListingPrepDesc: '解锁以使用AI自动生成您的畅销书描述和关键词。',
    royaltyCalculator: '版税计算器',
    royaltyCalculatorDesc: '解锁以计算您的KDP版税并优化定价策略。',
    // Prep Dashboard
    preparingMetadata: '正在准备Amazon元数据...',
    generatingMetadata: '正在生成描述、副标题和关键词...',
    pageCount: '页数',
    spineLabel: '书脊',
    trimLabel: '裁切',
    bleedLabel: '出血',
    bookDescription: '图书描述',
    preview: '预览',
    html: 'HTML',
    previewFormatted: '预览（已格式化）',
    editHtml: '编辑HTML',
    writeBestSellingDesc: '撰写畅销书描述',
    copyHtmlNote: '预览显示格式化文本。复制按钮复制原始HTML用于Amazon KDP。',
    authorLabel: '作者',
    generateSubtitle: '生成副标题',
    keywords: '关键词',
    generateAll: '全部生成',
    keywordsNote: '关键词避免重复标题中的词语以获得更好的Amazon排名。',
    // Footer
    aiDisclaimer: 'AI生成内容仅供创意灵感参考。非专业建议。',
  },
  ja: {
    join: '参加',
    signIn: 'ログイン',
    signOut: 'ログアウト',
    search: '検索',
    searchPlaceholder: '今日は何を学びたいですか？',
    whereToStay: '宿泊先',
    theVibe: '雰囲気',
    downloadPDF: 'PDFダウンロード',
    aCuratedGuide: 'キュレーションガイド',
    printPreview: '印刷プレビュー',
    newGuide: '新しいガイド',
    dashboard: 'ダッシュボード',
    myProjects: 'マイプロジェクト',
    saveToLibrary: 'ライブラリに保存',
    localResources: '地域リソース',
    enableLocation: '位置情報を有効にする',
    chapterOne: '第1章',
    chapterTwo: '第2章',
    chapterThree: '第3章',
    tableOfContents: '目次',
    commonMistakes: 'よくある間違い',
    proTips: 'プロのヒント',
    keyTakeaways: '重要ポイント',
    loading: '読み込み中...',
    generating: 'ガイドを生成中...',
    tryAgain: '再試行',
    powered_by: '提供',
    introductionTo: '入門',
    weaving: 'ガイドを織り上げ中...',
    downloadFreeSample: '無料サンプルをダウンロード (PDF)',
    unlockFullGuide: '完全な職人ガイドをアンロック',
    puttingItIntoPractice: '実践する',
    saving: '保存中...',
    saved: 'ライブラリに保存されました',
    learnAnything: '何でも学べます。',
    beautifulGuides: 'あなただけのために作られた美しいカスタムガイド。',
    searchExamples: '試してみてください:「サワードウパンの焼き方」または「水彩画の基礎」',
    freeSampleDesc: '無料サンプルには表紙、目次、第1章が含まれています。完全ガイドは全章をアンロックします。',
    fullAccessUnlocked: 'フルアクセスがアンロックされました',
    beginReading: '読み始める',
    advancedOptions: '詳細オプション',
    narrativeVoice: 'ナラティブボイス',
    bookStructure: 'ブック構造',
    focusAreas: 'フォーカスエリア',
    // Focus Area Labels
    focus_history: '歴史',
    focus_wellness: 'ウェルネス',
    focus_nightlife: 'ナイトライフ',
    focus_art: 'アート＆デザイン',
    focus_luxury: 'ラグジュアリー',
    focus_culture: '地元の文化',
    focus_nature: '自然',
    // Focus Area Tooltips
    tooltip_history: '古代の物語、文化遺産、歴史年表',
    tooltip_wellness: 'スパ、リトリート、瞑想、セルフケア',
    tooltip_nightlife: 'バー、クラブ、ライブ音楽、ナイトライフ',
    tooltip_art: 'ギャラリー、建築、スタジオ、クリエイティブスペース',
    tooltip_luxury: 'ハイエンド体験、専用会場、プレミアムサービス',
    tooltip_culture: '伝統、地元の習慣、食品市場、コミュニティライフ',
    tooltip_nature: '公園、ハイキングトレイル、ビーチ、アウトドアアドベンチャー',
    // Voice Labels
    voice_insider: 'インサイダー',
    voice_bestie: '親友',
    voice_poet: '詩人',
    voice_professor: '教授',
    // Voice Tooltips
    tooltip_insider: 'キュレーション、クール、「知る人ぞ知る」',
    tooltip_bestie: '生意気、自信、ウィット',
    tooltip_poet: '夢のような、華やか、ロマンチック',
    tooltip_professor: 'アカデミック、教育的、明確',
    // Structure Labels
    structure_curated: 'キュレーションガイド',
    structure_playbook: 'プレイブック',
    structure_balanced: 'バランス',
    // Structure Tooltips
    tooltip_curated: 'フォーカス：場所、ホテル、レストラン、ショッピング',
    tooltip_playbook: 'フォーカス：実践、ハウツー、儀式、教育',
    tooltip_balanced: '教育と目的地の50/50ミックス',
    // Weaving Steps
    weaving_step1: '糸を集めています...',
    weaving_step2: '織機を準備しています...',
    weaving_step3: '章を織っています...',
    weaving_step4: '仕上げを追加しています...',
    weaving_step5: 'もうすぐ完成...',
    // Chapter Status
    status_reading: '読書中',
    status_expand: '展開',
    status_drafting: '下書き中...',
    status_pending: '保留中',
    status_locked: 'ロック済み',
    chapters: '章',
    contents: '内容',
    // Block Labels
    keyTakeaway: '重要ポイント',
    proTip: 'プロのヒント',
    // Download/Progress
    downloadFullGuide: '完全ガイドをダウンロード (PDF)',
    generatingPdf: 'PDFを生成中...',
    weavingPages: '織り上げ中... {count} ページ',
    pleaseWaitChapters: 'すべての章をお待ちください...',
    artisanWeaving: '職人があなたのカスタム詳細を織り上げています...',
    // Navigation
    prev: '前へ',
    next: '次へ',
    pageTools: 'ページツール',
    fit: 'フィット',
    fullSize: '100%',
    pageOf: '/',
    chapterOf: '第{current}章 / 全{total}章',
    // Page Tools Menu
    premiumEditingSuite: 'プレミアム編集スイート',
    insertPageBefore: '前にページを挿入',
    insertPageAfter: '後にページを挿入',
    searchGallery: 'ギャラリーを検索',
    uploadOwnPhoto: '自分の写真をアップロード',
    tryIt: '試してみて！',
    regenerateChapter: '第{n}章を再生成',
    editPageContent: 'ページコンテンツを編集',
    deleteThisPage: 'このページを削除',
    bwPrintMode: '白黒印刷モード',
    bwPrintModeDesc: 'Amazonのより安価な白黒印刷に最適化',
    // Image States
    searchingArchives: 'アーカイブを検索中...',
    searching: '検索中...',
    aiSelected: 'AI選択',
    imageNotFound: '画像が見つかりません',
    // Cover Studio
    coverStudio: 'カバースタジオ',
    previewStudio: 'プレビュースタジオ',
    kdpCoverStudioTitle: 'KDPカバースタジオ＆エクスポートマネージャー',
    // Tab Labels
    tabFront: '表紙',
    tabBack: '裏表紙',
    tabSpine: '背表紙',
    tabWrap: '完全版',
    tabPrep: '準備',
    tabRoyalty: '$$$',
    tabExport: 'エクスポート',
    // Front Tab
    currentFrontCover: '現在の表紙',
    editCoverText: 'カバーテキストを編集',
    viewOnly: '閲覧のみ',
    titleLabel: 'タイトル',
    subtitleLabel: 'サブタイトル',
    saveTextChanges: 'テキスト変更を保存',
    uploadYourOwnImage: 'または自分の画像をアップロード',
    uploadCustomCoverDesc: 'カスタムカバー画像をアップロード（JPG、PNG、最大5MB）',
    uploadCoverImage: 'カバー画像をアップロード',
    customCoverImage: 'カスタムカバー画像',
    unlockCoverEditing: 'カバー編集をアンロック',
    coverBranding: 'カバーブランディング',
    brand: 'ブランド',
    logo: 'ロゴ',
    uploadLogo: 'ロゴをアップロード',
    changeLogo: 'ロゴを変更',
    reset: 'リセット',
    premium: 'プレミアム',
    noImage: '画像なし',
    uploading: 'アップロード中...',
    // Back Tab
    currentBackCover: '現在の裏表紙',
    backCoverText: '裏表紙テキスト',
    header: 'ヘッダー',
    // Export Tab
    completeKdpPackage: '完全KDPパッケージ',
    kdpPackageDesc: 'Amazon KDPに必要なすべてを1つのZIPファイルでダウンロード：',
    coverFile: '背表紙付きフルラップカバー',
    manuscriptFile: '目次と画像付き本文',
    kindleEbook: 'Kindle eBook形式',
    kindleCover: 'eBookカバー画像',
    downloadKdpPackage: 'KDPパッケージをダウンロード',
    generatingPackage: '生成中...',
    // Locked Tab Content
    amazonListingPrep: 'Amazonリスト準備',
    amazonListingPrepDesc: 'AIでベストセラー説明とキーワードを自動生成するにはアンロックしてください。',
    royaltyCalculator: 'ロイヤリティ計算機',
    royaltyCalculatorDesc: 'KDPロイヤリティを計算し、価格戦略を最適化するにはアンロックしてください。',
    // Prep Dashboard
    preparingMetadata: 'Amazonメタデータを準備中...',
    generatingMetadata: '説明、サブタイトル、キーワードを生成中...',
    pageCount: 'ページ数',
    spineLabel: '背表紙',
    trimLabel: 'トリム',
    bleedLabel: '裁ち落とし',
    bookDescription: '本の説明',
    preview: 'プレビュー',
    html: 'HTML',
    previewFormatted: 'プレビュー（フォーマット済み）',
    editHtml: 'HTMLを編集',
    writeBestSellingDesc: 'ベストセラー説明を書く',
    copyHtmlNote: 'プレビューはフォーマット済みテキストを表示。コピーボタンはAmazon KDP用の生HTMLをコピー。',
    authorLabel: '著者',
    generateSubtitle: 'サブタイトルを生成',
    keywords: 'キーワード',
    generateAll: 'すべて生成',
    keywordsNote: 'キーワードはAmazonランキング向上のためタイトル内の単語の重複を避けます。',
    // Footer
    aiDisclaimer: 'AI生成コンテンツはクリエイティブなインスピレーション専用です。専門的なアドバイスではありません。',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    // Try to load from localStorage
    const stored = localStorage.getItem('loom_language');
    if (stored && SUPPORTED_LANGUAGES.some(l => l.code === stored)) {
      return stored as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('loom_language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const currentLanguage = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
