import { Link } from 'react-router-dom';
import Logo from '@/components/Logo';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-md border-b border-border/50">
        <div className="container flex items-center justify-between h-16">
          <Link to="/" className="hover:opacity-70 transition-opacity">
            <Logo />
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="container py-12 max-w-2xl mx-auto">
        <h1 className="font-serif text-3xl md:text-4xl font-semibold text-foreground mb-8">
          Terms of Service
        </h1>
        
        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-muted-foreground">
          <p className="text-sm text-muted-foreground/70">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">Creative Inspiration Only</h2>
            <p>
              Loom & Page is designed for <strong>creative inspiration and educational exploration only</strong>. 
              The AI-generated guides are meant to spark ideas and provide general information, not to serve as 
              authoritative instructions or professional advice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">No Professional Advice</h2>
            <p>
              Content generated by Loom & Page should <strong>not</strong> be used as a substitute for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Professional legal advice from a licensed attorney</li>
              <li>Medical advice from a qualified healthcare provider</li>
              <li>Financial advice from a certified professional</li>
              <li>Expert guidance in any specialized field</li>
            </ul>
            <p>
              Always consult qualified professionals for matters requiring expertise.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">AI-Generated Content</h2>
            <p>
              All guides are created using artificial intelligence. While we strive for accuracy, AI-generated 
              content may contain errors, omissions, or outdated information. You are responsible for verifying 
              any information before acting on it.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">Acceptable Use</h2>
            <p>
              By using Loom & Page, you agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the service for lawful purposes only</li>
              <li>Not attempt to generate harmful, illegal, or inappropriate content</li>
              <li>Understand that generated content is for inspiration, not instruction</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">Limitation of Liability</h2>
            <p>
              Loom & Page and its creators are not liable for any damages arising from the use of our service 
              or reliance on AI-generated content. Use at your own discretion.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-xl font-medium text-foreground">Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service constitutes acceptance 
              of any changes.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <Link to="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            ← Back to Home
          </Link>
        </div>
      </main>
    </div>
  );
};

export default TermsOfService;
