import { useState, useCallback, useEffect, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Sparkles, Copy, Check, RefreshCw, Eye, Code } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { formatDimensions } from '@/lib/kdpUtils';
import WeavingLoader from '@/components/WeavingLoader';
import { useLanguage } from '@/contexts/LanguageContext';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface KdpPrepDashboardProps {
  title: string;
  topic: string;
  subtitle?: string;
  authorName: string;
  contentPageCount: number;
  bookData?: any;
}

const MAX_DESCRIPTION_LENGTH = 4000;

const KdpPrepDashboard = ({
  title,
  topic,
  subtitle: initialSubtitle,
  authorName,
  contentPageCount,
  bookData,
}: KdpPrepDashboardProps) => {
  const { t, language } = useLanguage();
  
  // Metadata state
  const [localSubtitle, setLocalSubtitle] = useState(initialSubtitle || '');
  const [author, setAuthor] = useState(authorName);
  const [description, setDescription] = useState('');
  const [keywords, setKeywords] = useState<string[]>(Array(7).fill(''));
  
  // View mode for description (preview vs edit) - default to preview for better readability
  const [descriptionViewMode, setDescriptionViewMode] = useState<'preview' | 'edit'>('preview');
  
  // Loading states
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false);
  const [isGeneratingSubtitle, setIsGeneratingSubtitle] = useState(false);
  const [isGeneratingKeywords, setIsGeneratingKeywords] = useState(false);
  const [copiedDescription, setCopiedDescription] = useState(false);
  
  // Auto-generation tracking
  const hasAutoGenerated = useRef(false);
  const [isInitialLoading, setIsInitialLoading] = useState(false);
  
  // Get formatted dimensions for display
  const dims = formatDimensions(contentPageCount);
  
  // Auto-generate on mount if fields are empty
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (!title) return;
    
    // Mark as triggered immediately to prevent duplicate calls
    hasAutoGenerated.current = true;
    
    // Check which fields need generation
    const needsDescription = !description;
    const needsSubtitle = !localSubtitle;
    const needsKeywords = keywords.every(k => !k);
    
    // If all fields are already populated, skip
    if (!needsDescription && !needsSubtitle && !needsKeywords) return;
    
    setIsInitialLoading(true);
    
    // Generate all needed fields in parallel
    const promises: Promise<boolean>[] = [];
    if (needsDescription) promises.push(generateDescription());
    if (needsSubtitle) promises.push(generateSubtitle());
    if (needsKeywords) promises.push(generateKeywords());
    
    Promise.all(promises).finally(() => {
      setIsInitialLoading(false);
    });
  }, [title]);
  
  // Generate description with AI (internal function)
  const generateDescription = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-book-v2', {
        body: {
          mode: 'kdp-description',
          title,
          topic,
          subtitle: localSubtitle,
          bookData,
          language,
        },
      });
      
      if (error) throw error;
      
      if (data?.description) {
        setDescription(data.description.slice(0, MAX_DESCRIPTION_LENGTH));
        return true;
      }
    } catch (err) {
      console.error('Failed to generate description:', err);
    }
    return false;
  };
  
  // Generate subtitle with AI (internal function)
  const generateSubtitle = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-book-v2', {
        body: {
          mode: 'kdp-subtitle',
          title,
          topic,
          language,
        },
      });
      
      if (error) throw error;
      
      if (data?.subtitle) {
        setLocalSubtitle(data.subtitle);
        return true;
      }
    } catch (err) {
      console.error('Failed to generate subtitle:', err);
    }
    return false;
  };
  
  // Generate keywords with AI (internal function)
  const generateKeywords = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-book-v2', {
        body: {
          mode: 'kdp-keywords',
          title,
          topic,
          subtitle: localSubtitle,
          language,
        },
      });
      
      if (error) throw error;
      
      if (data?.keywords && Array.isArray(data.keywords)) {
        const newKeywords = [...data.keywords.slice(0, 7)];
        while (newKeywords.length < 7) newKeywords.push('');
        setKeywords(newKeywords);
        return true;
      }
    } catch (err) {
      console.error('Failed to generate keywords:', err);
    }
    return false;
  };
  
  // Handler for manual description regeneration
  const handleGenerateDescription = useCallback(async () => {
    setIsGeneratingDescription(true);
    const success = await generateDescription();
    if (success) {
      toast.success('Best-selling description generated!');
    } else {
      toast.error('Failed to generate description');
    }
    setIsGeneratingDescription(false);
  }, [title, topic, localSubtitle, bookData]);
  
  // Handler for manual subtitle regeneration
  const handleGenerateSubtitle = useCallback(async () => {
    setIsGeneratingSubtitle(true);
    const success = await generateSubtitle();
    if (success) {
      toast.success('Subtitle generated!');
    } else {
      toast.error('Failed to generate subtitle');
    }
    setIsGeneratingSubtitle(false);
  }, [title, topic]);
  
  // Handler for manual keywords regeneration
  const handleGenerateKeywords = useCallback(async () => {
    setIsGeneratingKeywords(true);
    const success = await generateKeywords();
    if (success) {
      toast.success('7 unique keywords generated!');
    } else {
      toast.error('Failed to generate keywords');
    }
    setIsGeneratingKeywords(false);
  }, [title, topic, localSubtitle]);
  
  // Copy HTML description to clipboard
  const handleCopyDescription = useCallback(async () => {
    if (!description) {
      toast.error('No description to copy');
      return;
    }
    
    try {
      await navigator.clipboard.writeText(description);
      setCopiedDescription(true);
      toast.success('HTML code copied to clipboard! Paste directly into Amazon KDP.');
      setTimeout(() => setCopiedDescription(false), 2000);
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  }, [description]);
  
  // Update single keyword
  const handleKeywordChange = (index: number, value: string) => {
    const newKeywords = [...keywords];
    newKeywords[index] = value;
    setKeywords(newKeywords);
  };
  
  // Show loading state while auto-generating
  if (isInitialLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full min-h-[400px] gap-6">
        <WeavingLoader text={t('preparingMetadata')} />
        <p className="text-sm text-muted-foreground">
          {t('generatingMetadata')}
        </p>
      </div>
    );
  }
  
  return (
    <div className="space-y-4 h-full">
      {/* Live Specs Header Bar */}
      <div className="flex flex-wrap items-center justify-center gap-4 p-3 bg-muted/50 rounded-lg border">
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">{t('pageCount')}:</span>
          <span className="text-sm font-medium">{dims.pageCount}</span>
        </div>
        <div className="h-4 w-px bg-border" />
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">{t('spineLabel')}:</span>
          <span className="text-sm font-medium">{dims.spineWidth}</span>
        </div>
        <div className="h-4 w-px bg-border" />
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">{t('trimLabel')}:</span>
          <span className="text-sm font-medium">{dims.trimSize}</span>
        </div>
        <div className="h-4 w-px bg-border" />
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">{t('bleedLabel')}:</span>
          <span className="text-sm font-medium">{dims.bleed}</span>
        </div>
      </div>
      
      {/* Two-Column Grid */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 flex-1">
        {/* Column 1: Description (60% width) */}
        <div className="md:col-span-3 flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <Label htmlFor="description" className="text-sm font-medium">
              {t('bookDescription')}
            </Label>
            <div className="flex items-center gap-2">
              <span className={`text-xs ${description.length > MAX_DESCRIPTION_LENGTH * 0.9 ? 'text-destructive' : 'text-muted-foreground'}`}>
                {description.length} / {MAX_DESCRIPTION_LENGTH}
              </span>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" size="sm" className="gap-1 h-7">
                    {descriptionViewMode === 'preview' ? (
                      <>
                        <Eye className="w-3 h-3" />
                        {t('preview')}
                      </>
                    ) : (
                      <>
                        <Code className="w-3 h-3" />
                        {t('html')}
                      </>
                    )}
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="bg-popover z-50">
                  <DropdownMenuItem onClick={() => setDescriptionViewMode('preview')}>
                    <Eye className="w-4 h-4 mr-2" />
                    {t('previewFormatted')}
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => setDescriptionViewMode('edit')}>
                    <Code className="w-4 h-4 mr-2" />
                    {t('editHtml')}
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          
          {descriptionViewMode === 'preview' ? (
            <div 
              className="flex-1 min-h-[200px] p-4 rounded-md border border-input bg-background overflow-auto prose prose-sm dark:prose-invert max-w-none"
              dangerouslySetInnerHTML={{ 
                __html: description || '<span class="text-muted-foreground italic">Your formatted description will appear here...</span>' 
              }}
            />
          ) : (
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value.slice(0, MAX_DESCRIPTION_LENGTH))}
              placeholder="Your Amazon book description with HTML tags (<b>, <ul>, <li>)..."
              className="flex-1 min-h-[200px] font-mono text-sm resize-none"
            />
          )}
          
          <div className="flex gap-2">
            <Button
              onClick={handleGenerateDescription}
              disabled={isGeneratingDescription}
              variant="default"
              className="gap-2"
            >
              {isGeneratingDescription ? (
                <RefreshCw className="w-4 h-4 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4" />
              )}
              {t('writeBestSellingDesc')}
            </Button>
            
            <Button
              onClick={handleCopyDescription}
              variant="outline"
              disabled={!description}
              size="icon"
              title="Copy HTML to Clipboard"
            >
              {copiedDescription ? (
                <Check className="w-4 h-4" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
            </Button>
          </div>
          
          <p className="text-xs text-muted-foreground">
            {t('copyHtmlNote')}
          </p>
        </div>
        
        {/* Column 2: Metadata Fields (40% width) */}
        <div className="md:col-span-2 space-y-4">
          {/* Title (Locked) */}
          <div>
            <Label htmlFor="title" className="text-sm font-medium">{t('titleLabel')}</Label>
            <Input
              id="title"
              value={title}
              disabled
              className="mt-1 bg-muted"
            />
          </div>
          
          {/* Author */}
          <div>
            <Label htmlFor="author" className="text-sm font-medium">{t('authorLabel')}</Label>
            <Input
              id="author"
              value={author}
              onChange={(e) => setAuthor(e.target.value)}
              placeholder="Author name..."
              className="mt-1"
            />
          </div>
          
          {/* Subtitle */}
          <div>
            <Label htmlFor="subtitle" className="text-sm font-medium">{t('subtitleLabel')}</Label>
            <div className="flex gap-2 mt-1">
              <Input
                id="subtitle"
                value={localSubtitle}
                onChange={(e) => setLocalSubtitle(e.target.value)}
                placeholder="Book subtitle..."
                className="flex-1"
              />
              <Button
                onClick={handleGenerateSubtitle}
                disabled={isGeneratingSubtitle}
                variant="outline"
                size="icon"
                title={t('generateSubtitle')}
              >
                {isGeneratingSubtitle ? (
                  <RefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
              </Button>
            </div>
          </div>
          
          {/* Keywords Grid */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <Label className="text-sm font-medium">{t('keywords')} ({keywords.filter(k => k).length}/7)</Label>
              <Button
                onClick={handleGenerateKeywords}
                disabled={isGeneratingKeywords}
                variant="outline"
                size="sm"
                className="gap-1"
              >
                {isGeneratingKeywords ? (
                  <RefreshCw className="w-3 h-3 animate-spin" />
                ) : (
                  <Sparkles className="w-3 h-3" />
                )}
                {t('generateAll')}
              </Button>
            </div>
            <div className="grid grid-cols-1 gap-2">
              {keywords.map((keyword, index) => (
                <Input
                  key={index}
                  value={keyword}
                  onChange={(e) => handleKeywordChange(index, e.target.value)}
                  placeholder={`Keyword ${index + 1}...`}
                  className="text-sm"
                />
              ))}
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              {t('keywordsNote')}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default KdpPrepDashboard;
